### ISSUE TITLE
Tuya Smart Air Box (AirBox04) mixes up CO2 and Formaldehyde data

### ISSUE THREAD

**Issue by mateon1** [Koenkk/zigbee2mqtt#11033]
### What happened?

Connected a Zigbee-based Tuya AirBox04 sensor to Zigbee2MQTT, the device was detected as a [TS0601_air_quality_sensor](https://www.zigbee2mqtt.io/devices/TS0601_air_quality_sensor.html), and started rapidly reporting sensor values, but the "formaldehyd" value is suspiciously high, and "co2" value is suspiciously low. Comparing the data from this device to a near-identical WiFi-based device, I can tell the VOC is wired up correctly, but co2 and formaldehyde were swapped.

Example message:
```
info MQTT publish: topic 'zigbee2mqtt/[REDACTED]', payload '{"co2":2,"formaldehyd":368,"humidity":42,"last_seen":"2022-01-26T18:19:12+01:00","linkquality":123,"temperature":19.9,"voc":1}'
```

### What did you expect to happen?

All reported values were correct.

### How to reproduce it (minimal and precise)

Pair an AirBox04 device to Zigbee2MQTT, observe logs.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20210120

### Adapter

Some CCxx62 device with zStack3x0

**Comment by mateon1** [comment]
I looked through the debug messages, to me it looks like:
The `"dp":2` messages should be formaldehyde.
The `"dp":18` - temperature, which they already are.
The `"dp":19` - humidity, permille, but always a multiple of 10. Seem to be handled correctly.
The `"dp":21` - seem to be voc, and already handled correctly.
The `"dp":22` - match up with CO2 on the Wifi device, currently affects "formaldehyde" in the output.

**Comment by bigsem89** [comment]
i've also got a problem with this device.
My coordinator is breaking due to too spamming

**Comment by frfstu** [comment]
I'm use zigbee2mqtt version 1.22.0-2, coordinator zStack3x0 firmware 20211217
![Screenshot_20220206-203618~2](https://user-images.githubusercontent.com/87616721/152705569-0895379f-1c65-461e-9d74-3d4cf45c169c.png)
![Screenshot_20220206-210020](https://user-images.githubusercontent.com/87616721/152705614-1ab67ced-f329-48e5-b057-5ca16037eadb.png)
![Screenshot_20220206-210005](https://user-images.githubusercontent.com/87616721/152705615-ab636cd4-f81b-4a4c-bd85-f6ab59c69913.png)
![Screenshot_20220206-205947](https://user-images.githubusercontent.com/87616721/152705618-cf56b1d0-c4a3-45c7-86fd-28bbc3bd03d3.png)
![Screenshot_20220206-205939](https://user-images.githubusercontent.com/87616721/152705619-d4f4da1e-fb4f-4650-bc2e-fc918b941579.png)
![Screenshot_20220206-205931](https://user-images.githubusercontent.com/87616721/152705620-0a62ab7a-9cfe-403d-a16a-a6eb4fc03b8b.png)
TS0601 _TZE200_ryfmq5rl Air quality sensor not only are the output parameters of carbon dioxide and formaldehyde sensors mixed up, but this device sends so many data reports every second that my server can’t cope with their processing and freezes, doesn’t display (can’t load) the history of indicators, because of this, they work every other time  automation based on this device's data, spamming logs unnecessarily filling disk space and constantly writing and rewriting data to the disk has already disabled two microSD cards and one solid state drive.  I have previously written about this issue.
![IMG_20220206_174814](https://user-images.githubusercontent.com/87616721/152706027-77fb738f-bcf4-4a47-960e-45c9d5838899.jpg)

**Comment by debnetjm** [comment]
I can confirm this issue as well. 
<img width="562" alt="Screenshot 2022-03-06 115406" src="https://user-images.githubusercontent.com/11645774/156920054-a1b9a5f3-e722-4619-8264-aaaddf07e7f7.png">

device is reporting values few times per second
`Zigbee2MQTT:info  2022-03-06 11:52:35: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":156,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:35+01:00","linkquality":131,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:35: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":138,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:35+01:00","linkquality":123,"temperature":23,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:36: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":342,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:36+01:00","linkquality":123,"temperature":23,"voc":1}'
Zigbee2MQTT:info  2022-03-06 11:52:36: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":2,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":131,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:36+01:00","linkquality":123,"temperature":23,"voc":1}'
Zigbee2MQTT:info  2022-03-06 11:52:36: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":2,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":140,"formaldehyd":368,"humidity":28,"last_seen":"2022-03-06T11:52:36+01:00","linkquality":131,"temperature":23,"voc":1}'
Zigbee2MQTT:info  2022-03-06 11:52:37: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":2,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":656,"formaldehyd":368,"humidity":28,"last_seen":"2022-03-06T11:52:37+01:00","linkquality":127,"temperature":23,"voc":1}'
Zigbee2MQTT:info  2022-03-06 11:52:37: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":2,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":142,"formaldehyd":368,"humidity":28,"last_seen":"2022-03-06T11:52:37+01:00","linkquality":131,"temperature":23.1,"voc":1}'
Zigbee2MQTT:info  2022-03-06 11:52:37: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":2,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":31,"formaldehyd":368,"humidity":28,"last_seen":"2022-03-06T11:52:37+01:00","linkquality":127,"temperature":23.1,"voc":1}'
Zigbee2MQTT:info  2022-03-06 11:52:37: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":2,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":120,"formaldehyd":368,"humidity":28,"last_seen":"2022-03-06T11:52:37+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:37: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":167,"formaldehyd":368,"humidity":28,"last_seen":"2022-03-06T11:52:37+01:00","linkquality":123,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:37: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":139,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:37+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:38: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":469,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:38+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:38: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":120,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:38+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:38: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":113,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:38+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:39: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":584,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:39+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:39: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":154,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:39+01:00","linkquality":131,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:39: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":122,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:39+01:00","linkquality":127,"temperature":23.1,"voc":0}'
Zigbee2MQTT:info  2022-03-06 11:52:39: MQTT publish: topic 'zigbee2mqtt/Czujnik CO2 75', payload '{"co2":1,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Czujnik CO2 75","hardwareVersion":1,"ieeeAddr":"0xa4c1384acfbd1b52","manufacturerID":4417,"manufacturerName":"_TZE200_ryfmq5rl","model":"TS0601_air_quality_sensor","networkAddress":62755,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"elapsed":141,"formaldehyd":358,"humidity":28,"last_seen":"2022-03-06T11:52:39+01:00","linkquality":131,"temperature":23.1,"voc":0}'`

**Comment by Koenkk** [comment]
Swapping should already have been fixed in z2m 1.25.0 (https://github.com/Koenkk/zigbee-herdsman-converters/pull/3982)

**Comment by debnetjm** [comment]
Seems it is not (maybe not for all devices ?)

latest-dev: Zigbee2MQTT version 1.25.0-dev commit: [ad24c4f]


{
    **"co2": 2,**
    "device": {
        "applicationVersion": 64,
        "dateCode": "",
        "friendlyName": "Czujnik CO2 75",
        "hardwareVersion": 1,
        "ieeeAddr": "0xa4c1384acfbd1b52",
        "manufacturerID": 4417,
        "manufacturerName": "_TZE200_ryfmq5rl",
        "model": "TS0601_air_quality_sensor",
        "networkAddress": 20635,
        "powerSource": "Mains (single phase)",
        "stackVersion": 0,
        "type": "Router",
        "zclVersion": 3
    },
    **"formaldehyd": 368,**
    "humidity": 34,
    "last_seen": "2022-04-02T12:22:15+02:00",
    "linkquality": 105,
    "temperature": 19.2,
    "voc": 1,
    "elapsed": 414
}

**Comment by frfstu** [comment]
This is embarrassing!  The prospect of reconfiguring half of the server
configuration, additional installation of core library components, flashing
the stick (which, as the list of bug reports shows, also does not work
quite correctly).  And how the system will behave with these innovations is
not yet clear!  At the moment, I don’t have the opportunity (mainly related
to redundancy) to somehow contribute to the development and test new
versions of the software, no matter how trite it sounds, I renamed their
names in the display form  solves the problem itself with the correctness
of sending and the frequency of updating values, but purely visually
acceptable and correct.

сб, 2 апр. 2022 г., 13:25 Jaroslaw Michalak ***@***.***>:

**Comment by Koenkk** [comment]
@debnetjm also fixed it for the `_TZE200_ryfmq5rl` now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by skandragon** [comment]
> 

I don't get what you are saying here.  It's just the zigbee2mqtt that needs updated here, not the firmware on the zigbee devices.

**Comment by frfstu** [comment]
Jokers .. I read all this yesterday (crossed out today) as I imagined that
I would have to re-configure almost everything (including some
automations), I was just indescribably delighted!

сб, 2 апр. 2022 г., 21:26 Michael Graff ***@***.***>:

**Comment by debnetjm** [comment]
@Koenkk something's changed, co2 seems to be OK I am not sure about formaldehyd

formaldehyd seems to be too high and too similar to co2 reading (see graph)

<img width="922" alt="image" src="https://user-images.githubusercontent.com/11645774/161521405-f32a9699-1bce-4161-90e3-4fe5842e6d29.png">


using latest-dev

{
    "co2": 358,
    "device": {
        "applicationVersion": 64,
        "dateCode": "",
        "friendlyName": "Czujnik CO2 75",
        "hardwareVersion": 1,
        "ieeeAddr": "0xa4c1384acfbd1b52",
        "manufacturerID": 4417,
        "manufacturerName": "_TZE200_ryfmq5rl",
        "model": "TS0601_air_quality_sensor",
        "networkAddress": 20635,
        "powerSource": "Mains (single phase)",
        "stackVersion": 0,
        "type": "Router",
        "zclVersion": 3
    },
    "elapsed": 1109,
    "formaldehyd": 368,
    "humidity": 37,
    "last_seen": "2022-04-04T11:51:17+02:00",
    "linkquality": 102,
    "pm25": 1,
    "temperature": 19.1,
    "voc": 1
}

**Comment by kevincaradant** [comment]
Hi

I just fall on this thread but maybe you should remove the device completely and add it again because I just connected mine yesterday, and I got value close to 0 until 10 for the formaldehyd attribute so I don't understand yours :)
![image](https://user-images.githubusercontent.com/6093175/161705342-db612aa5-26ce-4195-9321-2be7ba68d768.png)

**Comment by Koenkk** [comment]
@debnetjm could be that yours uses different data point ids, to figure them out follow https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#requirements-and-caveats

**Comment by debnetjm** [comment]
@Koenkk they seems to be OK but DPs are not fixed for Smart Air Box in tuya.js

    // tuya smart air box
    tuyaSabCO2: 2,
    tuyaSabTemp: 18,
    tuyaSabHumidity: 19,
    tuyaSabVOC: 21,
    tuyaSabFormaldehyd: 22,

DP 18: temperature 2022-04-06 09:55:13	Report	Current Temperature	22.10℃	device itself

DP 2: CH20 (formaldehyd) 2022-04-06 09:53:34	Report	CH2O value	0.01mg/m³	device itself

DP 19: humidity 2022-04-06 09:54:00	Report	Current Humidity	39.00%	device itself

DP 21: VOC 2022-04-06 09:56:08	Report	VOC value	0.10ppm	device itself	

DP 22: CO2 2022-04-06 09:56:00	Report	CO2 value	368ppm	device itself

My device Smart Air Box (AirBox04) does not support PM25, does not show in tuya app as well.
Seems my airbox04 was detected as Smart Air House Keeper which probably support pm25 ?

**Comment by Koenkk** [comment]
@debnetjm are correct values reported when paired through the TuYa app and can you provide the data/database.db entry of your device?

**Comment by debnetjm** [comment]
![Screenshot_20220406-193546_Tuya Smart](https://user-images.githubusercontent.com/11645774/162035857-0a0c6037-d857-4d12-8bdf-aababb22ccee.jpg)

`{"id":42,"type":"Router","ieeeAddr":"0xa4c1384acfbd1b52","nwkAddr":43621,"manufId":4417,"manufName":"_TZE200_ryfmq5rl","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\"��)f\"��)\u0012","65506":32,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE200_ryfmq5rl","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1649266861521,"defaultSendRequestWhen":"immediate"}`

**Comment by debnetjm** [comment]
@Koenkk any update? Do you need any other information ?

**Comment by Koenkk** [comment]
@debnetjm pushed another fix, can you check if it works?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Mirarkitty** [comment]
Just got my TS0601 air quality thing with pm25 today, came here for this bug. I guess it's fixed now but not in the released branch?

In latest master:
{"co2":397,"formaldehyd":396,"humidity":41.8,"linkquality":153,"pm25":6,"temperature":25.4,"voc":52}

Previously co2 was 5-7... I'll see if I can get around to test the dev branch

**Comment by debnetjm** [comment]
@Koenkk indeed seems to be much better

two things:
1)
formaldehyd - missing unit name (mg/m³)
voc - I think should be ppm not ppb

2)
scale for formaldehyd and voc, I think itshould be 0.01-0.02 (formaldehyd) and 0.0-0.1 for voc as per screenshot from tuya application and definition from tuya platform ?

ch2o_value | Integer | { "unit": "mg/m³", "min": 0, "max": 1000, "scale": 2, "step": 1 }
voc_value | Integer | { "unit": "ppm", "min": 0, "max": 999, "scale": 1, "step": 1 }

`
Zigbee2MQTT:info  2022-04-26 14:27:17: MQTT publish: topic 'zigbee2mqtt/0xa4c1384acfbd1b52', payload '{"co2":368,"formaldehyd":2,"humidity":40,"last_seen":"2022-04-26T14:27:16+02:00","linkquality":138,"temperature":24.3,"voc":1}'
Zigbee2MQTT:info  2022-04-26 14:27:32: MQTT publish: topic 'zigbee2mqtt/0xa4c1384acfbd1b52', payload '{"co2":368,"formaldehyd":2,"humidity":39,"last_seen":"2022-04-26T14:27:31+02:00","linkquality":149,"temperature":24.3,"voc":1}'
Zigbee2MQTT:info  2022-04-26 14:28:02: MQTT publish: topic 'zigbee2mqtt/0xa4c1384acfbd1b52', payload '{"co2":368,"formaldehyd":2,"humidity":39,"last_seen":"2022-04-26T14:28:01+02:00","linkquality":149,"temperature":24.3,"voc":1}'
Zigbee2MQTT:info  2022-04-26 14:28:09: MQTT publish: topic 'zigbee2mqtt/0xa4c1384acfbd1b52', payload '{"co2":368,"formaldehyd":2,"humidity":39,"last_seen":"2022-04-26T14:28:08+02:00","linkquality":153,"temperature":24.3,"voc":1}'
Zigbee2MQTT:info  2022-04-26 14:28:16: MQTT publish: topic 'zigbee2mqtt/0xa4c1384acfbd1b52', payload '{"co2":358,"formaldehyd":1,"humidity":39,"last_seen":"2022-04-26T14:28:15+02:00","linkquality":149,"temperature":24.3,"voc":0}'
Zigbee2MQTT:info  2022-04-26 14:28:46: MQTT publish: topic 'zigbee2mqtt/0xa4c1384acfbd1b52', payload '{"co2":358,"formaldehyd":1,"humidity":39,"last_seen":"2022-04-26T14:28:45+02:00","linkquality":123,"temperature":24.3,"voc":0}'
`


`{
    "last_seen": "2022-04-26T14:17:57+02:00",
    "linkquality": 149,
    "co2": 358,
    "formaldehyd": 1,
    "humidity": 40,
    "temperature": 24.1,
    "voc": 1
}`

<img width="536" alt="image" src="https://user-images.githubusercontent.com/11645774/165298314-d651cbfc-4961-4d36-93ff-3e271a465417.png">

**Comment by Mirarkitty** [comment]
I'm seeing a lot of trash pm25 values, should those be filtered on zigbee2mqtt level or later? 

{ "co2": 378, "formaldehyd": 396, "humidity": 34.5, "linkquality": 153, "pm25": 43691, "temperature": 25.6, "voc": 37 }

43691 is 0xaaab, basically the bitfield "1010101010...". Seeing 43692 too (0xaaac). Normal pm25 for the sensor is around 5.

**Comment by Koenkk** [comment]
@debnetjm so basically ch20 should be divided by 100 and voc by 10?

**Comment by Koenkk** [comment]
@debnetjm fixed now

@Mirarkitty `0xaaab` `pm25` will be ignored now.

@Aaike can you try with the latest dev first? 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by ravimohta** [comment]
> @debnetjm fixed now
> 
> @Mirarkitty `0xaaab` `pm25` will be ignored now.
> 
> @Aaike can you try with the latest dev first? 
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Hi,

The erroneous pm25 value is 43692, which is 0xaaac (and not 0xaaab).

I have 4 of Tuya Air Quality monitor sensors and I switched to using the Edge version of the Z2m yesterday night. But I can still see the high pm25 coming.

Could you please check and fix this?

Regards

**Comment by ravimohta** [comment]
[![Screenshot_20220511_085706_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/86021590/167800681-8b4a05c9-9cd8-4651-a1a8-8b6394294e66.jpg)

**Comment by Koenkk** [comment]
@ravimohta fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Mirarkitty** [comment]
> The erroneous pm25 value is 43692, which is 0xaaac (and not 0xaaab).

It's both, as what I wrote above:

> 43691 is 0xaaab, basically the bitfield "1010101010...". Seeing 43692 too (0xaaac).

**Comment by ravimohta** [comment]
> > The erroneous pm25 value is 43692, which is 0xaaac (and not 0xaaab).
> 
> It's both, as what I wrote above:
> 
> > 43691 is 0xaaab, basically the bitfield "1010101010...". Seeing 43692 too (0xaaac). 
> 
> Possibly other values too, I get random spikes, but I haven't investigated more. My pm25 sensor seems to only give noise near zero otherwise, I can't get it to read any dust. 
> 
> I opened it and the pm25 sensor is jammed shut towards the bottom and top of the box (???), could be the reason. Will have to print a new case or run it open, I guess. Also co2, formaldehyde and voc are weirdly linked. None of this is the fault of zigbee2mqtt, though, I'm sure.
> 
> ![image](https://user-images.githubusercontent.com/3462581/167894974-1b6879ae-3708-4623-91be-fad93ae09be8.png)
> 

Sorry 🙏 my fault.. I agree, it is both these value.

Also please let share if running it open makes any difference or not.

Thanks

**Comment by Koenkk** [comment]
Ignored both values now (`0xaaac` and `0xaaab`)

**Comment by ravimohta** [comment]
Here is the min/max parameters, as mentioned in the paper that came with the sensor
![IMG_20220511_183331.jpg](https://user-images.githubusercontent.com/86021590/167911691-d24b952b-6c5b-4637-991e-4fce758be1f4.jpg)

**Comment by ravimohta** [comment]
I have reinstalled the Z2m Edge on home assistant and I am still seeing the high values every now and then.

How do I check if I have got the changes you applied via z2m Edge in home assistant?

**Comment by Mirarkitty** [comment]
To make it less spammy I recommend debounce or set cache flags to false. https://www.zigbee2mqtt.io/guide/configuration/mqtt.html#mqtt-behaviour

I burned a paper next to mine now. Zero difference on the pm25, still same noise between 3 and 10 units.

**Comment by kevincaradant** [comment]
Hi

I'm not sure it will be enought. Because I'm agree in Z2M and HA we will have only few messages. 
But I saw that my CC1352-P2 has many issues few days after and I think it's because the Tuya device will spam and 'kill' after few days the stability of the Zigbee coordinator.

Am I right to think this ? 

Since I disconnected the device, I didn't have any issues after that :(

Thank you for your advice on this

**Comment by Mirarkitty** [comment]
It could very well be. It's sending 5 messages every 5 seconds or so. I don't seem to have issues with my CC2652 luckily. It's probably outside the control of zigbee2mqtt since it doesn't seem to have a parameter for how often it should send.

Since I don't get **__any__** useful data from the device I will probably disconnect it anyway and I really can't recommend it. Maybe I can use it as a temp/hum sensor...

**Comment by Mirarkitty** [comment]
If anyone got any useful data out of the device I'd like to know :D

**Comment by ravimohta** [comment]
I still occasionally see pm2.5 values greater than 1000 (more in the range of around 40k or so). Since filtering the pm2.5 values, they have become lot less. And every day or two I run a sql query on the HA database and delete the records with pm2.5 values greater than 1000.

This has helped a lot in seeing the actual values of pm2.5

Next I played around with the debounce setting and tried different numbers (and I have 4 of these Tuya Air Quality devices) .. setting to 1 or 2 didnt make much of a different, so I tried 10 for a few days. Meaning I set the debounce on each of my Tuya air quality devices to 10 and let it run for 3-4 days to see what difference it made. After this period i realised that value of 10 really made the device useless .. the measured values of pm2.5, co2, voc, formaldehyde etc would change once in a few hours .. which made them useless really.

Eventually, after some more trial and error I have settled for a value of 5 or 6 as that slows down the refresh of readings from these devices to roughly once every 30 seconds or so, and I am happy with that.

Hope that helps.

**Comment by Mirarkitty** [comment]
How do your graphs look like? Mine are incredibly stupid:

![image](https://user-images.githubusercontent.com/3462581/170929253-02c28864-4e88-4f17-8b47-91600a6f41df.png)

This is definitely not a problem with z2m. (I turned off the cache myself, so I only get values when they come in and not all of them when any value comes in.)

**Comment by ravimohta** [comment]
The values I am getting now looks OK.

**Comment by ravimohta** [comment]
The values I am getting now seems ok. Please eee screenshots

**Comment by ravimohta** [comment]
![Screenshot_20220530_084156_io.homeassistant.companion.android_edit_2249780842777540.jpg](https://user-images.githubusercontent.com/86021590/170943828-5e625360-21e6-4edc-9289-394d63ba2f57.jpg)

**Comment by ravimohta** [comment]
![Screenshot_20220530_084211_io.homeassistant.companion.android_edit_2249767838597854.jpg](https://user-images.githubusercontent.com/86021590/170943857-6692de86-8b35-44ae-ac63-c065c351bb37.jpg)

**Comment by ravimohta** [comment]
![Screenshot_20220530_084225_io.homeassistant.companion.android_edit_2249751641099940.jpg](https://user-images.githubusercontent.com/86021590/170943899-2a86ad65-adb6-40c5-b821-018849d4f5d0.jpg)

**Comment by ravimohta** [comment]
![Screenshot_20220530_084316_io.homeassistant.companion.android_edit_2249724741731194.jpg](https://user-images.githubusercontent.com/86021590/170943936-2bc7162f-e758-4c8c-918d-f8841d999eed.jpg)

**Comment by ravimohta** [comment]
![Screenshot_20220530_084323_io.homeassistant.companion.android_edit_2249706409774947.jpg](https://user-images.githubusercontent.com/86021590/170943964-d543b0a5-b009-4308-ab29-a0affbfa2996.jpg)

**Comment by ravimohta** [comment]
![Screenshot_20220530_084331_io.homeassistant.companion.android_edit_2249691021343699.jpg](https://user-images.githubusercontent.com/86021590/170943994-c2ccb072-32c8-4948-aa3a-85bd473aabf8.jpg)

**Comment by ravimohta** [comment]
My only issue now is that the formaldehyde, voc and co2 seem to be linked, or very similar all the times.

**Comment by buddy31130** [comment]
mine are OK now
![air](https://user-images.githubusercontent.com/83547288/171047233-1ff9bf91-d4f5-4565-a108-20d30cbb6841.PNG)
Sorry, I don't use temperature nor humidity

**Comment by Mirarkitty** [comment]
> My only issue now is that the formaldehyde, voc and co2 seem to be linked, or very similar all the times.

Yes, this. They seem to be based on the same measurement, but with different scales and baselines. I don't think the firmware does what it should, because they have different sensors. pm25 just gives random spikes for me, I should put it outside the box and see if it helps...

**Comment by buddy31130** [comment]
After updating, the debounce does not seem to work anymore. It generates tons of data... About every 1-4 sec with debouce set to any value

**Comment by aredridel** [comment]
I get seemingly okay data from the pm25 sensor if I delete anything over 40k; not just the filtering added recently.

<img width="1328" alt="Screen Shot 2022-06-03 at 22 20 48" src="https://user-images.githubusercontent.com/2876/171974473-e650c700-b437-4d29-8a0a-e5d3715509d5.png">

**Comment by frfstu** [comment]
I apologize for the inaccurate translation, but I think the general meaning
is clear.  I am now suing the state authorities of the Russian Federation
(I have a court date on April 13, 2022), whose officials fabricate medical
and other documents related to the accident that happened to me, exposing
it as a chronic disease, hinting at the fact that it is hereditary, thereby
depriving me of all the prescribed  the law of benefits, benefits, care,
treatment, because of this I cannot receive compensation from the state,
the payment of insurance, and I am paid a minimum pension which is barely
enough to buy food for a month (and by law, multi-million compensation must
be paid for an industrial injury).

сб, 2 апр. 2022 г., 13:25 Jaroslaw Michalak ***@***.***>:
