### ISSUE TITLE
Bosch Radiator Thermostats II (Bosch BTH-RA) become inaccessible after some time

### ISSUE THREAD

**Issue by Uarml** [Koenkk/zigbee2mqtt#16376]
### What happened?

A few days after pairing The Bosch Thermostats 2 I can't communicate with them anymore.
The ZigBee stick is only 5 meters away from the thermostats.
Full reboot makes all thermostats functional again, whereas a simple restart does not.
Maybe they go in sleep mode or something like that. 
I have a thermostat in my bathroom, i can still communicate with it. 
Maybe it doesn't go in a sleep mode because it is often switched to window open and closed mode.

### What did you expect to happen?

After pairing thermostats should be available permanently.

### How to reproduce it (minimal and precise)

Pair thermostats and wait.

### Zigbee2MQTT version

1.29.2 running on Home Assistant

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle plus

### Debug log

Publish 'set' 'system_mode' to 't.w.h' failed: 'Error: Write 0x18fc26000003b444/1 hvacThermostat({"16391":{"value":5,"type":48}}, {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4617,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'

**Comment by erzhan89** [comment]
Same issue...

**Comment by Uarml** [comment]
> Same issue...  
> 

That's bad.

**Comment by mipoat** [comment]
Could it be this one is related to: https://github.com/Koenkk/zigbee2mqtt/issues/13478 where the TRV gets unresponsive when connected to the coordinator but works flawless when connected via a router?

**Comment by Uarml** [comment]
> Could it be this one is related to: #13478 where the TRV gets unresponsive when connected to the coordinator but works flawless when connected via a router?

Maybe, but i can't test it now because, i've no router devices at the moment.

**Comment by BBJake** [comment]
As commented in https://github.com/Koenkk/zigbee2mqtt/issues/13478 it seems to be definitiv the same problem.
A have this problems only if my thermostat is connected to the Coordinator. Devices that are connected to a route have no problem!
I have this problem with Bosch Thermostat II, but not with Saswell TS0601 (Hama).
Also look here: https://github.com/Koenkk/zigbee2mqtt/issues/13478#issuecomment-1383942462

**Comment by Uarml** [comment]
Thank you.

**Comment by gekberlin** [comment]
I also have the same issue with an Sonoff Zigbee Dongle Plus. In my case the issue beginns even after just a few hours.

**Comment by Uarml** [comment]
> I also have the same issue with an Sonoff Zigbee Dongle Plus. In my case the issue beginns even after just a few hours.

Sometimes this happens after a few hours after pairing and sometimes after a few days.

**Comment by BBJake** [comment]
There seems to be hope for a fix to this problem... 
#https://github.com/Koenkk/zigbee2mqtt/issues/13478#issuecomment-1432643349

**Comment by xdubx** [comment]
Yes same over here. Sonoff Zigbee 3.0 USB Dongle Plus. With stock firmware. After the device is not reachable in the log don't a publish message appears.

**Comment by slugzero** [comment]
There is a new firmware available for testing which should fix this issue: [20230410](https://github.com/Koenkk/Z-Stack-firmware/tree/f5a6270875cc13d32387524b54d460c9b6274841/coordinator/Z-Stack_3.x.0/bin)

**Comment by mldytech** [comment]
> There is a new firmware available for testing which should fix this issue: [20230410](https://github.com/Koenkk/Z-Stack-firmware/tree/f5a6270875cc13d32387524b54d460c9b6274841/coordinator/Z-Stack_3.x.0/bin)

Just for information: For me the issue seems to be fixed. I'm running 3 bosch TRVs for over a week now without any issues. Thanks!

**Comment by xdubx** [comment]
me too.

**Comment by xdubx** [comment]
F.y.i. after one month they disconnects. ....

**Comment by lieblinger** [comment]
Still having the same issue on latest Z2M with Sonoff E-Dongle on stock firmware. Is there something I can do (firmware update)?

**Comment by xdubx** [comment]
Iam driving curently 20230507. You can find it here. https://www.zigbee2mqtt.io/guide/adapters/#recommended. But my rtvs still disconnects.

**Comment by xdubx** [comment]
@Uarml  can you approve the new firmware fix the issue? And reopen the bug?

**Comment by Uarml** [comment]
> @Uarml can you approve the new firmware fix the issue? And reopen the bug?

I haven't used my thermostats for quite a while, the last time was around early March. Back then, all thermostats except one worked. Maybe I'll try to connect them again and see what happens, if you would like to.
