### ISSUE TITLE
Third Reality smart plug with power missing decimal

### ISSUE THREAD

**Issue by artbird309** [Koenkk/zigbee2mqtt#16646]
### What happened?

I added four new ZigBee smart plugs Third Reality BLE smart plug with power (3RSP02028BZ) it connects fine and turns off and on but the power metering data is without a decimal point (e.g. 1159 instead of 115.9). This plug was recently added by @weihuan1111 in PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/5093

State: from one of the plugs: 
`{
    "current": 26,
    "last_seen": "2023-02-12T19:15:28-05:00",
    "linkquality": 109,
    "power": 13,
    "state": "ON",
    "voltage": 1206
}`

### What did you expect to happen?

I expected the state to be 1.3W and 120.6V.

### How to reproduce it (minimal and precise)

Connect 3RSP02028BZ and load and read power metering data. 

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

 20221226

### Adapter

SMLIGHT SLZB-06 running CC2652P

**Comment by Vendo232** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/44098230/221258353-e2f3f36b-8755-40ed-94da-814be32ca2fe.png)

**Comment by Vendo232** [comment]
using custom converter does not help either

`const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const ota = require('zigbee-herdsman-converters/lib/ota');

module.exports = [
    {
        zigbeeModel: ['3RSP02028BZ'],
        model: '3RSP02028BZ',
        vendor: 'Third Reality',
        description: 'Zigbee / BLE smart plug with power',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering],
        toZigbee: [tz.on_off],
        ota: ota.zigbeeOTA,
        exposes: [e.switch(), e.ac_frequency(), e.power(),e.power_factor(), e.energy(), e.current(), e.voltage().withAccess(ea.STATE)],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
            await endpoint.read('haElectricalMeasurement', ['acPowerMultiplier', 'acPowerDivisor']);
            await reporting.onOff(endpoint);
            await reporting.activePower(endpoint, {change: 10});
            await reporting.rmsCurrent(endpoint, {change: 50});
            await reporting.rmsVoltage(endpoint, {change: 5});
            await reporting.readMeteringMultiplierDivisor(endpoint);
            endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
            endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {
                acVoltageMultiplier: 1, acVoltageDivisor: 10, acCurrentMultiplier: 1, acCurrentDivisor: 1000, acPowerMultiplier: 1, acPowerDivisor: 10,
            });
            device.save();
        },
    },
];`

![image](https://user-images.githubusercontent.com/44098230/221258589-c1d7a33d-2e00-47b7-a0a8-fdf1c22a4224.png)

**Comment by Automayted** [comment]
Same issue here.

**Comment by Koenkk** [comment]
Can you provide the debug log when the device reports power such that I can check if decimals are reported?

**Comment by Vendo232** [comment]
Hope thia is it

![Screenshot_20230226-072840](https://user-images.githubusercontent.com/44098230/221416746-6128f598-be36-40cc-95ce-4a9f6e910a82.png)

**Comment by artbird309** [comment]
Below is the debug log for one of my plugs, I do not see decimals being reported for any of the measurements (current, power, or voltage).
`Debug 2023-02-26 15:08:41Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":15}' from endpoint 1 with groupID 0
Info 2023-02-26 15:08:41MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":15,"last_seen":"2023-02-26T15:08:40-05:00","linkquality":91,"power":12,"state":"ON","voltage":1212}'
Debug 2023-02-26 15:08:41Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":15}' from endpoint 1 with groupID 0
Info 2023-02-26 15:08:41MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":15,"last_seen":"2023-02-26T15:08:40-05:00","linkquality":94,"power":12,"state":"ON","voltage":1212}'
Debug 2023-02-26 15:08:42Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":7}' from endpoint 1 with groupID 0
Info 2023-02-26 15:08:42MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":15,"last_seen":"2023-02-26T15:08:41-05:00","linkquality":94,"power":7,"state":"ON","voltage":1212}'
Debug 2023-02-26 15:08:42Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":7}' from endpoint 1 with groupID 0
Info 2023-02-26 15:08:42MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":15,"last_seen":"2023-02-26T15:08:41-05:00","linkquality":65,"power":7,"state":"ON","voltage":1212}'
Debug 2023-02-26 15:12:41Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":16}' from endpoint 1 with groupID 0
Info 2023-02-26 15:12:41MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":16,"last_seen":"2023-02-26T15:12:40-05:00","linkquality":105,"power":7,"state":"ON","voltage":1212}'
Debug 2023-02-26 15:12:41Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsVoltage":1214}' from endpoint 1 with groupID 0
Info 2023-02-26 15:12:41MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":16,"last_seen":"2023-02-26T15:12:40-05:00","linkquality":87,"power":7,"state":"ON","voltage":1214}'
Debug 2023-02-26 15:12:42Received Zigbee message from 'plug_name', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":7}' from endpoint 1 with groupID 0
Info 2023-02-26 15:12:42MQTT publish: topic 'zigbee2mqtt/plug_name', payload '{"current":16,"last_seen":"2023-02-26T15:12:41-05:00","linkquality":112,"power":7,"state":"ON","voltage":1214}'`

**Comment by weihuan1111** [comment]
I use our latest version(v1.00.41) of plug to test it. 
I put this code to my Z2M to test localy,  [https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/third_reality.js]
And this issue has been fixed, you can see screenshot below.
I will submit ota file to zigbee2mqtt, so you can update your plug to the latest.
![image](https://user-images.githubusercontent.com/99949392/221505112-4466a262-171c-41ed-aabd-eca9e94ffde8.png)

**Comment by Vendo232** [comment]
is use of converter file always going to be required? 

I`m on latest-dev released today and FW 1.00.41 and I do not see difference but I`m not using the js converter though.

**Comment by weihuan1111** [comment]
> it is fixed now, updated to 1.00.41 and restarted the z2m not using external converters
> 
> thank you.
> 
> ![image](https://user-images.githubusercontent.com/44098230/221716095-719309a2-402b-4dc8-b082-2b2f1467b9b3.png)

We have fix the energy issue in zigbee2mqtt and you can wait for the next version of zigbee2mqtt.

**Comment by Koenkk** [comment]
Fix will be included in the 1 February release. Thanks @weihuan1111 !

**Comment by Automayted** [comment]
I can confirm the latest-dev container and device firmware v1.00.41 resolved the voltage, current, and power readings, but total energy (kWh) is still not correct.

It appears the total energy reading is off by 100,000x - my 8.4W test load running for an hour reports 894.3kWh, not .008943kWh.

`{
    "ac_frequency": 60,
    "current": 0.13,
    "energy": 894.3,
    "last_seen": "2023-02-28T12:16:53-06:00",
    "linkquality": 108,
    "power": 8.4,
    "state": "ON",
    "update": {
        "installed_version": 268513322,
        "latest_version": 268513322,
        "state": "idle"
    },
    "voltage": 122,
    "power_factor": null,
    "update_available": null
}`

**Comment by tgkenney** [comment]
I have zigbee2mqtt version 1.30.2 running as a HAOS add-on, and firmware version v1.00.41 running on the device, but I'm still seeing this issue I believe.

I'm also not getting any energy reading from the device, the field is just showing as null.  No clue if I'm doing something wrong there.

`{
    "ac_frequency": 60,
    "current": 266,
    "linkquality": 212,
    "power": 30.2,
    "state": "ON",
    "update": {
        "installed_version": 268513322,
        "latest_version": 268513322,
        "state": "idle"
    },
    "voltage": 1185,
    "energy": null,
    "power_factor": null,
    "update_available": null
}`
