### ISSUE TITLE
TuYa TS0044_1 incorrect actions

### ISSUE THREAD

**Issue by rouloy** [Koenkk/zigbee2mqtt#17862]
### What happened?

Up until I updated my zigbee2mqtt docker today the actions where exactly the way they are described on here: https://www.zigbee2mqtt.io/devices/TS0044_1.html#tuya-ts0044_1

After the update it only exposes actions like "single" or "double" without any indication of the button I pressed.

### What did you expect to happen?

The actions exposes should be consistent with the description page: https://www.zigbee2mqtt.io/devices/TS0044_1.html#tuya-ts0044_1

### How to reproduce it (minimal and precise)

Latest Zigbee2mqtt docker running 
TuYa TS0044_1 connected
Click any button 

### Zigbee2MQTT version

    1.31.0 commit: f440c86

### Adapter firmware version

20211217

### Adapter

Electrolama zig-a-zig-ah!

**Comment by Iroamstaff** [comment]
Same problem for me since the update

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Soulfly999** [comment]
So when we can get the fix for it? Need this to Open and Close my Covers 😅

**Comment by roobbb** [comment]
Thank you very much for the fast fix and your great work. 

As a workaround I tried to put the fixing code lines from above (https://github.com/Koenkk/zigbee2mqtt/issues/17862) into the file "/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js". But it seems there is no changed behavior, even after full restart.

Is there any workaround available (better than my try 😅), wich we could set up till this fix gets into main branch? I would not like to switch to dev. If not, I can wait of course 😀

Thank you and kind regards

**Comment by Koenkk** [comment]
I pushed a good fix now (https://github.com/Koenkk/zigbee-herdsman-converters/commit/df01d077a944f139039054add18aeb08f68f252a)

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by jomuc** [comment]
@roobbb 
> Is there any workaround available (better than my try sweat_smile), wich we could set up till this fix gets into main branch? I would not like to switch to dev. If not, I can wait of course grinning

I changed the version for zigbee-herdsman-converters in `package.json`
`"zigbee-herdsman-converters": "15.17.0",`
then run
`npm install`
and finally
`restart zigbee2mqtt service`

Be aware, that you have to revert your change before using update.sh the next time.

**Comment by ElminsterAU** [comment]
My Z2M was just (half an hour ago) updated to [1.31.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.31.1) commit: [3572c60](https://github.com/Koenkk/zigbee2mqtt/commit/3572c60) and I'm now having exactly this problem.

all my [TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html#tuya-ts0044) are now only giving me "single" instead of "1_single", "2_single", ... actions. And all my automations are broken.

the exact devices I have are:

Zigbee Model
TS0044
Zigbee Manufacturer
_TZ3000_wkai4ga5
Description
Wireless switch with 4 buttons
Manufacturer
[TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model
[TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html#tuya-ts0044)

**Comment by ElminsterAU** [comment]
Reverting to the 1.31.0 docker image and it works again...

**Comment by ElminsterAU** [comment]
Yes, but only tomorrow. I'm just going to bed after re-enabling my ability to turn my lights off from there...

**Comment by Soulfly999** [comment]
Same for my TS0044_1 updated it for a hour, restartet HA+Zigbee2mqtt but the buttons doesn't work. 
But the button actions are shown in my automation "1_single", "2_single" and so on...

**Comment by ElminsterAU** [comment]
> @ElminsterAU can you check with the latest-dev tag?

@Koenkk I was just going to try it, but saw that you've released a new "latest" and "1.31.2" at the same time, so I just tried out the latest, which reports itself as [1.31.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.31.2) commit: [21f5125](https://github.com/Koenkk/zigbee2mqtt/commit/21f5125), so I've tried that one and it seems to work correctly for me.

**Comment by firstnamegit** [comment]
Thanks! working again after update.

**Comment by Anashost** [comment]
Issue fixed Thanks
> Zigbee Model TS0041
> Zigbee Manufacturer _TZ3000_itb0omhv
> 
> &
> 
> Zigbee Model TS0042
> Zigbee Manufacturer _TZ3000_tzvbimpq
> 
> &
> 
> Zigbee Model TS0043 
> Zigbee Manufacturer _TZ3000_sj7jbgks
>

**Comment by Anashost** [comment]
@tampiss have you tried to hold the button until its light turns off then immediately release?
My TS0043, 42, 41 works that way.

I've TS0044 coming soon which i supposed they will work that way, as the code in the converters page supports that as i see here:
```
zigbeeModel: ['TS0044'],
        model: 'TS0044',
        vendor: 'TuYa',
        description: 'Wireless switch with 4 buttons',
        whiteLabel: [
            {vendor: 'Lonsonho', model: 'TS0044'}, {vendor: 'Haozee', model: 'ESW-OZAA-EU'},
            {vendor: 'LoraTap', model: 'SS6400ZB'}, {vendor: 'Moes', model: 'ZT-SY-EU-G-4S-WH-MS'},
            tuya.whitelabel('Moes', 'ZT-SR-EU4', 'Star Ring 4 Gang Scene Switch', ['_TZ3000_a4xycprs']),
            tuya.whitelabel('TuYa', 'TS0044_1', 'Zigbee 4 button remote - 12 scene', ['_TZ3000_dziaict4']),
        ],
        fromZigbee: [fz.tuya_on_off_action, fz.battery],
        exposes: [e.battery(), e.action(['1_single', '1_double', '1_hold', '2_single', '2_double', '2_hold',
            '3_single', '3_double', '3_hold', '4_single', '4_double', '4_hold'])],
        toZigbee: [],
        configure: tuya.configureMagicPacket,
```

**Comment by tampiss** [comment]
> @tampiss have you tried to hold the button until its light turns off then immediately release? My TS0043, 42, 41 works that way.
> 
> I've TS0044 coming soon which i supposed they will work that way too, as the code in the converters page supports that as i see here:
> 
> ```
> zigbeeModel: ['TS0044'],
>         model: 'TS0044',
>         vendor: 'TuYa',
>         description: 'Wireless switch with 4 buttons',
>         whiteLabel: [
>             {vendor: 'Lonsonho', model: 'TS0044'}, {vendor: 'Haozee', model: 'ESW-OZAA-EU'},
>             {vendor: 'LoraTap', model: 'SS6400ZB'}, {vendor: 'Moes', model: 'ZT-SY-EU-G-4S-WH-MS'},
>             tuya.whitelabel('Moes', 'ZT-SR-EU4', 'Star Ring 4 Gang Scene Switch', ['_TZ3000_a4xycprs']),
>             tuya.whitelabel('TuYa', 'TS0044_1', 'Zigbee 4 button remote - 12 scene', ['_TZ3000_dziaict4']),
>         ],
>         fromZigbee: [fz.tuya_on_off_action, fz.battery],
>         exposes: [e.battery(), e.action(['1_single', '1_double', '1_hold', '2_single', '2_double', '2_hold',
>             '3_single', '3_double', '3_hold', '4_single', '4_double', '4_hold'])],
>         toZigbee: [],
>         configure: tuya.configureMagicPacket,
> ```

True. My fault. I did not wait long enough. Thank you. M

**Comment by Soulfly999** [comment]
> Same for my TS0044_1 updated it for a hour to 1.31.1, restartet HA+Zigbee2mqtt but the buttons doesn't work. But the button actions are shown in my automation "1_single", "2_single" and so on...

For me it is fixed now, thank you

**Comment by rouloy** [comment]
New update fixed the problem

**Comment by roobbb** [comment]
Yes, it is working again even inside my docker environment 😎
Thank you very much 😀

**Comment by plevrier** [comment]
Since the laste update this seems to be an issue again? I have 2 of TS0044 switches and both not working any more. The only visible action in HA automation is "2_hold action" the others are gone.

Running on:
HA : 2024.1.4
MQTT : 6.4.0
Z2M : 1.35.1-1

![image](https://github.com/Koenkk/zigbee2mqtt/assets/6578301/2b2229af-cd9c-4654-bfd0-a84d797ee759)

**Comment by Bushrider** [comment]
Same problem here.
Actions are now labelled as 1_single 1_double etc...
Previous actions (single, double, hold) are still present but not working anymore.
Z2m version 1.35.2-1

**Comment by meifi** [comment]
same problem here ... 1.35.2 @ HA Addon

Payload in infolog shows correct value but z2m action shows null / empty string

MQTT publish: topic 'zigbee2mqtt/EG Kinderzimmer', payload '{"action":"","battery":100,"last_seen":"2024-02-04T11:07:08+01:00","linkquality":57,"voltage":3000}'
Info 2024-02-04 11:07:08MQTT publish: topic 'zigbee2mqtt/EG Kinderzimmer/action', payload '4_single'


Ausgelöstes Ereignis (z.B. ein Aktivieren eines Tasters)
String ohne Inhalt("")

**Comment by CocoLeo3680** [comment]
Hi
I have Star Ring 4 Gang Wireless Scene Switch connected to zigbee2mqtt with skyconnect.
Model ZT-SR-EU4 manufactured by Moes
Zigbee ID: TS0044

No actions are showed. Only two automatism are avaliable (battery and linkquality)

https://ibb.co/qnjr7Fg


Thanks

**Comment by a10kiloham** [comment]
_TZ3000_wkai4ga5

Same issue here with the buttons not being detected properly. Available choices are limited to 1_single, 2_single, 3_single, 4_single and 2_double.

**Comment by e-p-s** [comment]
> same problem here ... 1.35.2 @ HA Addon
> 
> Payload in infolog shows correct value but z2m action shows null / empty string
> 
> MQTT publish: topic 'zigbee2mqtt/EG Kinderzimmer', payload '{"action":"","battery":100,"last_seen":"2024-02-04T11:07:08+01:00","linkquality":57,"voltage":3000}' Info 2024-02-04 11:07:08MQTT publish: topic 'zigbee2mqtt/EG Kinderzimmer/action', payload '4_single'
> 
> Ausgelöstes Ereignis (z.B. ein Aktivieren eines Tasters) String ohne Inhalt("")

Same for me. Empty string.

Zigbee-Modell
TS0044
Zigbee-Hersteller
_TZ3000_wkai4ga5

Current version: 1.40.1-1

**Comment by AlbertoAbruzzo** [comment]
> > same problem here ... 1.35.2 @ HA Addon
> > Payload in infolog shows correct value but z2m action shows null / empty string
> > MQTT publish: topic 'zigbee2mqtt/EG Kinderzimmer', payload '{"action":"","battery":100,"last_seen":"2024-02-04T11:07:08+01:00","linkquality":57,"voltage":3000}' Info 2024-02-04 11:07:08MQTT publish: topic 'zigbee2mqtt/EG Kinderzimmer/action', payload '4_single'
> > Ausgelöstes Ereignis (z.B. ein Aktivieren eines Tasters) String ohne Inhalt("")
> 
> Same for me. Empty string.
> 
> Zigbee-Modell TS0044 Zigbee-Hersteller _TZ3000_wkai4ga5
> 
> Current version: 1.40.1-1

The same for me, shows as "Empty string("")"

**Comment by Exellent1988** [comment]
same for me as @AlbertoAbruzzo

**Comment by Peterchen42** [comment]
Hello,
I have a similar problem here.
There are two mechanicly identical 12 scene remotes in use. One is detected as Tuya TS0044 (vendor _TZ3000_wbfgbpxq) that works fine. The other one is detected as Tuya TS0044 (vendor _TZ3000_j61x9rxn) and provides only the "1_hold" action and battery Level change as triggers.
Zigbee2MQTT-Version [1.42.0]
What can I do to fix it?

Thank you for helping

**Comment by mjaster** [comment]
Hallo, I have same problem like Peterchen42. Is there any solution?
Thanks,
