### ISSUE TITLE
Tuya smart curtain/new manufacture name

### ISSUE THREAD

**Issue by LirikToscanini** [Koenkk/zigbee2mqtt#19000]
### Link

https://www.zigbee2mqtt.io/devices/TS0601_cover_1.html

### Database entry

{"id":36,"type":"Router","ieeeAddr":"0xa4c138c66659b971","nwkAddr":53736,"manufId":4417,"manufName":"_TZE204_1fuxihti","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"���,g���,g���,f���,\u0012���,g���,g֐�,g","65506":56,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_1fuxihti","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1694939938012,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to connect another Tuya Curtain motor via z2m, but z2m identified it with a new manufacturer name '_TZE204_1fuxihti' , which is not in the list of official Tuya converters. I tried to make an external converter, but failed. device is not supported. please help. the previous 2 Tuya Curtain motors were identified without problems.

### External converter

```shell
const fz = require( 'zigbee-herdsman-converters/converters/fromZigbee' );
const tz = require( 'zigbee-herdsman-converters/converters/toZigbee' );
const exposes = require( 'zigbee-herdsman-converters/lib/exposes' );
const reporting = require( 'zigbee-herdsman-converters/lib/reporting' );
const extend = require( 'zigbee-herdsman-converters/lib/extend' );
const tuya = require( 'zigbee-herdsman-converters/lib/tuya' );
const e = exposes.presets;
const ea = exposes.access;

const definition = {
        zigbeeModel: [
            'owvfni3\u0000', 'owvfni3', 'u1rkty3', 'aabybja', // Curtain motors
            'mcdj3aq', 'mcdj3aq\u0000', // Tubular motors
            ],
        fingerprint: [
            { modelID: 'TS0601', manufacturerName: '_TZE204_1fuxihti' },
            ],
        model: 'TS0601',
        vendor: 'TuYa',
        description: 'Curtain motor/roller blind motor/window pusher/tubular motor',
        whiteLabel: [
            {vendor: 'Tuya', model: 'M515EGZT'},
            ],
        fromZigbee: [
            fz.tuya_cover,
            fz.ignore_basic_report,
            ],
        toZigbee: [
            tz.tuya_cover_control,
            tz.tuya_cover_options,
            ],
        exposes: [
            e.cover_position().setAccess('position', ea.STATE_SET),
            ],
    };

module.exports = definition;
```

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/72079b9919518c071406c9a5921de809

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by wildchai** [comment]
> Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/72079b9919518c071406c9a5921de809
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, check if issue is fixed

 Thanks for this. I had the same issue. With this it was resolved.

**Comment by LirikToscanini** [comment]
Thanks a lot,
 the issue is fixed with the external converter.

**Comment by Koenkk** [comment]
Integrated the fix, you can remove the ext converter after updating to the next release.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by gbrest** [comment]
Hey everyone! 👋

Just wanted to share a bit of my experience with the **MOES Zigbee Curtain Motor** (`_TZE204_1fuxihti`, model `TS0601`) and how I finally got it working in **Home Assistant with ZHA**, after a lot of digging and frustration.

---

📆 **As of mid-2025, the issue is still ongoing**

I bought a couple of these curtain motors in 2025 and paired them to Home Assistant using ZHA. To get them into pairing mode, I:

* Pressed the reset button **three times** quickly
* Then held it down until the LED started flashing

The device paired and showed up in the ZHA device list, but — **no entities appeared.**

---

❗**Why? Because it’s not really Zigbee-native**

This is another case of a Tuya TS0601 device. It communicates using Tuya’s proprietary MCU protocol over the `0xEF00` cluster, which is **not natively understood by ZHA**.

That’s why the device shows up, but doesn’t expose any entities or usable functionality unless you provide a **custom quirk**.

I found an old discussion where user **Prozpect** had posted a working quirk, but the link is gone. I had to do a deep dive across GitHub, Reddit and the Wayback Machine to find pieces of it and put it all back together.

---

🧩 **So here’s the full working solution, in one place, for rookies like me**

This is everything I did to get the curtain working properly with ZHA, including open/close/stop and position slider.

---

 ✅ **Step 1: Create the quirks folder**

Inside your `/config` directory (where `configuration.yaml` lives), create a new folder called:

**quirks**

So the full path is:

/config/quirks/

---

 ✅ **Step 2: Create an empty `__init__.py`**

Inside the `quirks` folder, create a new file called:

__init__.py

It can be completely empty, but it **must exist**.

---

 ✅ **Step 3: Create the custom quirk file**

Still inside the `quirks` folder, create a file called:

moes_curtain.py

And paste the following code into it (this is the full working quirk):

```

"""Tuya MCU based cover and blinds."""

from typing import Dict, Optional, Union
from zigpy.profiles import zha
import zigpy.types as t
from zigpy.zcl import foundation
from zigpy.zcl.clusters.closures import WindowCovering
from zigpy.zcl.clusters.general import (
    Basic,
    GreenPowerProxy,
    Groups,
    Ota,
    Scenes,
    Time,
)

from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.tuya import (
    NoManufacturerCluster,
    TUYA_MCU_COMMAND,
    TuyaLocalCluster,
    TuyaWindowCover,
    TuyaManufacturerWindowCover,
)
from zhaquirks.tuya.mcu import (
    DPToAttributeMapping,
    TuyaClusterData,
    TuyaMCUCluster,
)


class TuyaCC(t.enum8):
    """Tuya cover commands."""
    OPEN = 0x00
    STOP = 0x01
    CLOSE = 0x02


class ZclCC(t.enum8):
    """ZCL cover commands."""
    OPEN = 0x00
    CLOSE = 0x01
    STOP = 0x02


TUYA2ZB_COMMANDS = {
    ZclCC.OPEN: TuyaCC.OPEN,
    ZclCC.CLOSE: TuyaCC.CLOSE,
    ZclCC.STOP: TuyaCC.STOP,
}


class TuyaWindowCovering(NoManufacturerCluster, WindowCovering, TuyaLocalCluster):
    """Tuya MCU WindowCovering cluster."""

    attributes = WindowCovering.attributes.copy()
    attributes.update(
        {
            0xF000: ("curtain_switch", t.enum8, True),
            0xF001: ("accurate_calibration", t.enum8, True),
            0xF002: ("motor_steering", t.enum8, True),
            0xF003: ("travel", t.uint16_t, True),
        }
    )

    async def command(
        self,
        command_id: Union[foundation.GeneralCommand, int, t.uint8_t],
        *args,
        manufacturer: Optional[Union[int, t.uint16_t]] = None,
        expect_reply: bool = True,
        tsn: Optional[Union[int, t.uint8_t]] = None,
    ):
        """Override the default Cluster command."""

        self.debug(
            "Sending Tuya Cluster Command. Cluster Command is %x, Arguments are %s",
            command_id,
            args,
        )

        if command_id in (0x0002, 0x0000, 0x0001):
            cluster_data = TuyaClusterData(
                endpoint_id=self.endpoint.endpoint_id,
                cluster_name=self.ep_attribute,
                cluster_attr="curtain_switch",
                attr_value=TUYA2ZB_COMMANDS[command_id],
                expect_reply=expect_reply,
                manufacturer=-1,
            )
            self.endpoint.device.command_bus.listener_event(
                TUYA_MCU_COMMAND,
                cluster_data,
            )
            return foundation.GENERAL_COMMANDS[
                foundation.GeneralCommand.Default_Response
            ].schema(command_id=command_id, status=foundation.Status.SUCCESS)

        elif command_id == 0x0005:
            lift_value = args[0]

            cluster_data = TuyaClusterData(
                endpoint_id=self.endpoint.endpoint_id,
                cluster_name=self.ep_attribute,
                cluster_attr="current_position_lift_percentage",
                attr_value=lift_value,
                expect_reply=expect_reply,
                manufacturer=-1,
            )
            self.endpoint.device.command_bus.listener_event(
                TUYA_MCU_COMMAND,
                cluster_data,
            )
            return foundation.GENERAL_COMMANDS[
                foundation.GeneralCommand.Default_Response
            ].schema(command_id=command_id, status=foundation.Status.SUCCESS)

        self.warning("Unsupported command_id: %s", command_id)
        return foundation.GENERAL_COMMANDS[
            foundation.GeneralCommand.Default_Response
        ].schema(command_id=command_id, status=foundation.Status.UNSUP_CLUSTER_COMMAND)


class TuyaWindowCoverManufCluster(TuyaMCUCluster):
    """Tuya with WindowCover data points."""

    attributes = TuyaMCUCluster.attributes.copy()
    attributes.update(
        {
            0x5000: ("backlight_mode", t.enum8, True),
            0x8001: ("indicator_status", t.enum8, True),
        }
    )

    dp_to_attribute: Dict[int, DPToAttributeMapping] = {
        1: DPToAttributeMapping(
            TuyaWindowCovering.ep_attribute,
            "curtain_switch",
        ),
        2: DPToAttributeMapping(
            TuyaWindowCovering.ep_attribute,
            "current_position_lift_percentage",
        ),
        3: DPToAttributeMapping(
            TuyaWindowCovering.ep_attribute,
            "current_position_lift_percentage",
        ),
    }

    data_point_handlers = {
        1: "_dp_2_attr_update",
        2: "_dp_2_attr_update",
        3: "_dp_2_attr_update",
    }


class TuyaCover0601_GP(TuyaWindowCover):
    """Tuya blind controller device."""

    signature = {
        MODELS_INFO: [
            ("_TZE204_1fuxihti", "TS0601"),
        ],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.SMART_PLUG,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaWindowCoverManufCluster.cluster_id,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            },
            242: {
                PROFILE_ID: 41440,
                DEVICE_TYPE: 97,
                INPUT_CLUSTERS: [],
                OUTPUT_CLUSTERS: [GreenPowerProxy.cluster_id],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaWindowCoverManufCluster,
                    TuyaWindowCovering,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            },
            242: {
                PROFILE_ID: 41440,
                DEVICE_TYPE: 97,
                INPUT_CLUSTERS: [],
                OUTPUT_CLUSTERS: [GreenPowerProxy.cluster_id],
            },
        }
    }
```

---

✅ **Step 4: Tell ZHA to load custom quirks**

In your `configuration.yaml`, add or update the `zha:` section like this:

```
zha:
  custom_quirks_path: quirks
```

> **Do not** include `/config/quirks` — just `quirks`

---

 ✅ **Step 5: Restart and pair again**

1. Restart Home Assistant completely (not just ZHA).
2. Remove any previous pairing of the curtain motor.
3. Put the curtain back into pairing mode (3 presses, then long press).
4. Pair it again from **ZHA > Add Device**.

You should now see a new **`cover.xxxxxx` entity**, and you’ll be able to open/close/stop and use the position slider.

---

Let me know if this works for you or if you get stuck — happy to help!
