### ISSUE TITLE
Xiaomi SJCGQ11LM Water Sensor - False Positives

### ISSUE THREAD

**Issue by coolguymatt** [Koenkk/zigbee2mqtt#1967]
# Bug Report
## What happened
After updating to zigbee2mqtt to 1.6, I have received two false positives on two of my Xiaomi water leak sensors. For the first one, I could not get it to go back to Dry (Off). Removing and rejoining the device did not fix the issue so I completely removed it from the database manually and rejoined it. This seems to have fixed the first one. After about another hour, the second device had a false positive. It has the same behaviour - it does not go back to Dry (Off) when the device is dry.

## What did you expect to happen
Accurate water leak readings

## How to reproduce it (minimal and precise)
Random

## Debug Info
zigbee2mqtt version: 1.6
CC253X firmware version:  CC2531_DEFAULT_20190608.zip

**Comment by mpuff** [comment]
i also get a false "true" notification yesterday from a Xiaomi water leak sensor, i am also on zigbee2mqtt 1.6

**Comment by groenmarsmannetje** [comment]
I also have experienced this today. Sensor is still reporting leakage, but is dry. Even after removing battery and reconnect. I updated to version 1.6 just before this sensor turned on.

**Comment by ptvoinfo** [comment]
I've added this update to the latest version but my sensors work well. It seems we should an option (disable or enable) interval reports for these sensors. @Koenkk, what do think?

**Comment by Koenkk** [comment]
Im wondering if the converter is actually correct @ptvoinfo how do you know these are the correct values?

**Comment by ptvoinfo** [comment]
@Koenkk I've tested it with the real device and simulate water leaks. I have 2 sensors, both works identically.

**Comment by groenmarsmannetje** [comment]
But why has it changed? It used to work without any problems. My sensor is still reporting leakage and has become totally useless now.

**Comment by docBliny** [comment]
I started having the exact same issue. I currently have ~15 sensors going off causing me to get alerts throughout the day. I'm using zigbee2mqtt on Home Assistant. I see lines similar to the following in the Docker log:
```
zigbee2mqtt:info 9/15/2019, 12:08:06 PM MQTT publish: topic 'zigbee2mqtt/water_leak_1', payload '{"water_leak":true,"linkquality":2,"battery":100,"voltage":3065}
```

This started immediately after updating to 1.6.

**Comment by ptvoinfo** [comment]
The quick temporary workaround is to edit the following file:
node_modules\zigbee-shepherd-converters\devices.js
Find
`    {
        zigbeeModel: ['lumi.sensor_wleak.aq1'],
        model: 'SJCGQ11LM',
        vendor: 'Xiaomi',
        description: 'Aqara water leak sensor',
        supports: 'water leak true/false',
        fromZigbee: [
            fz.xiaomi_battery_3v, fz.SJCGQ11LM_water_leak_iaszone,
            fz.SJCGQ11LM_water_leak_interval, fz.ignore_basic_change,
        ],
        toZigbee: [],
    },`
and remove `fz.SJCGQ11LM_water_leak_interval, `.

**Comment by Koenkk** [comment]
Fixed in the dev branch (removed converter).

**Comment by ptvoinfo** [comment]
Can I add this converter as a device option? Because it works for some devices?

**Comment by Koenkk** [comment]
Yes

**Comment by gecata93** [comment]
This issue is marked as fixed(closed) but i still experience this problem, is the new version deployed  with this fix? And if yes? What i need to do, to get these changes? 

I'm using: Zigbee2mqtt Hass.io Add-on
Aqara water leak sensor (SJCGQ11LM)
Firmware: Zigbee2mqtt 1.6.0

**Comment by Koenkk** [comment]
@gecata93 it is not in zigbee2mqtt but in the latest dev (edge for hassio)

**Comment by gecata93** [comment]
@Koenkk  oh okay, thanks. When will be available for the stable(regular) version?

**Comment by Koenkk** [comment]
@gecata93 in zigbee2mqtt 1.7.0 (no eta)

**Comment by VivantSenior** [comment]
In my case simple trick helped. @gecata93, just try to simulate leak (connect two screws at the bottom of sensor) using wire or just put it in the cup with water. After few seconds break the wire circuit / remove sensor from the cup. Now the sensor should detect real leakage.

**Comment by apeeters** [comment]
I still experience this in 1.9.0 :(

**Comment by docBliny** [comment]
> I still experience this in 1.9.0 :(

I had that too on some sensors, but then found out that the battery was dead in those... Worth a check.

**Comment by groenmarsmannetje** [comment]
I only experience this after a restart of Home Assistant. I always have to restart Zigbee2Mqtt otherwise one water leak sensor will report that it detects water.

**Comment by apeeters** [comment]
I triggered a wet and dry cycle once and seems stable now. I will keep a close look at it for a few more days. Didn't replace the battery.

**Comment by apeeters** [comment]
As promised I report back: It is perfectly stable now: no more false positives.

**Comment by bbrendon** [comment]
Apparently, my house is flooding right now. All 3 of my sensors are triggered. The place is dry.
It's broken again. version 1.25.0

**Comment by mpuff** [comment]
I had the same yesterday on 2 of 3 sensors, also on 1.25.0

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/12018
