### ISSUE TITLE
Unable to pair Legrand socket 067725A 

### ISSUE THREAD

**Issue by jessycler** [Koenkk/zigbee2mqtt#21969]
### What happened?

When trying to pair new Legrand Socket 0677**25**A, it will be paired then it will left the network, pair and left in a loop.
it seems to be a new socket revision. socket manufactured 01/24

https://www.legrand.fr/pro/catalogue/prise-de-courant-connectee-celiane-with-netatmo-16a-3680w-avec-mesure-et-suivi-consommation-blanc-sans-plaque
![Screenshot_20240327-165945](https://github.com/Koenkk/zigbee2mqtt/assets/122178623/aaa84167-b626-40e5-9be2-bc4044c959e3)

### What did you expect to happen?

i expected that the socket stays connected...

### Zigbee2MQTT version

 1.36.0

### Adapter firmware version

20221226

### Adapter

SLZB-06

### Setup

Home assistant OS, VM Synology DS923+

**Comment by sjorge** [comment]
This is fixed in dev, the next release in April will also have it.

**Comment by jessycler** [comment]
Good news ! Nice ! Thx

**Comment by VincenzoMaletta** [comment]
Is it also valid for BTicino devices (that should be Legrand rebranded) ?

**Comment by sjorge** [comment]
> Is it also valid for BTicino devices (that should be Legrand rebranded) ?

Yes

**Comment by VincenzoMaletta** [comment]
I've just verified and it works fine. Great job. Unfortunatelly the on/off status oscillation that emerged with latest device firmwaredevice  (#21959) is not solved.
