### ISSUE TITLE
Unknown power state for Tuya TS0505B_2_1 zigbee light bulb

### ISSUE THREAD

**Issue by rursache** [Koenkk/zigbee2mqtt#24074]
### What happened?

After adding this light bulb:

Manufacturer: [Tuya](https://www.zigbee2mqtt.io/supported-devices/#v=Tuya)
Model: [TS0505B_2_1](https://www.zigbee2mqtt.io/devices/TS0505B_2_1.html#tuya-ts0505b_2_1)
Zigbee Model: TS0505B
Zigbee Manufacturer: _TZ3210_mja6r5ix

the "power" type stays as "unknown":

<img width="920" alt="image" src="https://github.com/user-attachments/assets/fc2f9500-697c-45c0-a487-2e1c61d7abda">

It works correctly however!

### What did you expect to happen?

The power type should be "plug" because its a light bulb

### How to reproduce it (minimal and precise)

1. Simply adding the device
2. Observe the wrong power state

### Zigbee2MQTT version

1.40.1 commit: 403d3c0

### Adapter firmware version

Irrelevant

### Adapter

Irrelevant

### Setup

Irrelevant

**Comment by Koenkk** [comment]
Fixed! After updating use the yellow reconfigure button on the device page to apply the fix and restart z2m.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by rursache** [comment]
after updating to zigbee2mqtt to [1.40.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.2) (commit [e06848d](https://github.com/Koenkk/zigbee2mqtt/commit/e06848d)) this light is now considered a
```
Zigbee RGB+CCT light
```
which is wrong. the image also changed. the details from my initial post here were correct.

the issue was that the "power" type stays as "unknown" (question mark).
this issue still happens even after using the "reconfigure" button 3 times + restarting zigbee2mqtt and the light itself

![ScreenShot 2024-10-02 at 17 30 27](https://github.com/user-attachments/assets/6aa722d5-2b99-4bd9-982b-e8d54773c466)

**Comment by Koenkk** [comment]
This was due to a mistake in https://github.com/Koenkk/zigbee-herdsman-converters/commit/3fe484c3326fb3bdbd5109c306af5acd6cbe0d59, fixed now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
