### ISSUE TITLE
Devices unavailable in HA after Z2M update

### ISSUE THREAD

**Issue by fhuebner2** [Koenkk/zigbee2mqtt#26562]
### What happened?

I can still control my devices via Zigbee2Mqtt GUI but not via Home Assistant anymore after update to 2.1.2-1

### Zigbee2MQTT version

2.1.2-1

### Adapter firmware version

0x26720700

### Adapter

Conbee2

### Setup

Add-On on Home Assistant on Raspi4

**Comment by MaJerle** [comment]
[Duplicate of #26557](https://github.com/Koenkk/zigbee2mqtt/issues/26557)

**Comment by Koenkk** [comment]
Fixed in 2.1.3!

**Comment by fhuebner2** [comment]
Thanks, when is release?

**Comment by Koenkk** [comment]
@fhuebner2 few mins from now

**Comment by boesing** [comment]
Hm, I do still have the same issue on 2.1.3 with zzh! on `20220219`.
Should I create a dedicated issue for that or can we have that handled in this one?
