### ISSUE TITLE
Ikea INSPELNING Smart plug E2206 raport Voltage, Power, Energy = 0

### ISSUE THREAD

**Issue by Jabol86** [Koenkk/zigbee2mqtt#27855]
### What happened?

I bought 3 ikea sockets. After adding to z2m on one of them all information appears, and then in two there is no data except amps.

Work:

![Image](https://github.com/user-attachments/assets/49940e63-7d7d-4589-ad49-8b1b83d6b97e)

Not work:

![Image](https://github.com/user-attachments/assets/f92b2531-b4b0-4bf2-93f5-6f3a727c1fab)

Soft:

![Image](https://github.com/user-attachments/assets/736c2316-d18d-4a9d-a2b8-4e395bc6764d)

### What did you expect to happen?

I wish they all worked :(

### Zigbee2MQTT version

2.4.0-1

### Adapter firmware version

20240710

### Adapter

SLZB-06 (CC2652P)

### Setup

Add-on on Home Assistant OS on gmtek g3 mini

### Debug log

[2025-06-30 22:26:02] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Suszarka new', payload '{"current":0.08,"energy":0,"identify":null,"linkquality":61,"power":0,"power_on_behavior":"previous","state":"ON","update":{"installed_version":33816645,"latest_version":33816645,"state":"idle"},"voltage":229.5}'

**Comment by mrmaximas** [comment]
try to re-configure plugs.

**Comment by Jabol86** [comment]
> try to re-configure plugs.

Try meny times ;/

**Comment by alex0411** [comment]
see #27750

**Comment by LeoeLeoeL** [comment]
This device (at least in Zigbee2MQTT) is absolutely unreliable to measure Wh.
see https://github.com/Koenkk/zigbee2mqtt/issues/27524
and https://github.com/Koenkk/zigbee2mqtt/issues/25929

I think lots of people who are using Ikea INSPELNING didn't realize that yet.

Somebody should write this issue in the SUPPORTED DEVICES section.

**Comment by mrmaximas** [comment]
Everything works for me as it has from day one.
<img width="1809" alt="Image" src="https://github.com/user-attachments/assets/365e74ca-6db3-4604-b4f6-66448616a067" />
<img width="494" alt="Image" src="https://github.com/user-attachments/assets/50850ac7-e2f1-419f-b31b-a38c8f987f3a" />

<img width="2051" alt="Image" src="https://github.com/user-attachments/assets/279dda46-a5e6-4ff6-aab5-af6233c76c9a" />

<img width="1981" alt="Image" src="https://github.com/user-attachments/assets/f403ea78-1190-491d-ab45-5db0b9ffc199" />

**Comment by LeoeLeoeL** [comment]
Issue appears under a very low load.
I think you cannot check that because your plug is monitoring an UPS.

**Comment by Jabol86** [comment]
> [#27750](https://github.com/Koenkk/zigbee2mqtt/issues/27750)

There is no solution provided. Nothing has been resolved.

**Comment by claymen** [comment]
> Issue appears under a very low load. I think you cannot check that because your plug is monitoring an UPS.

Interesting, as I've got one on a 3d printer which for the last half hour was pulling 700W and still didn't change the usage. I've got 12 or so of the plugs, and it's about 50/50 which ones report energy usage. All same firmware, and mixture of loads, some with constant loads around 50-60w showing energy consumption, others with variable loads like the printer showing none. Though they all report consistent wattage and voltage.

**Comment by LeoeLeoeL** [comment]
Today:

<img width="473" height="561" alt="Image" src="https://github.com/user-attachments/assets/a7a9efc7-71da-486d-8d85-d775f01772b6" />

Conumption increases of 250 watt/h two times while instant power is 1.5 watt.

**Comment by notDavid** [comment]
Same issue here, i just bought 2 of them;
1. Seems to work fine
2. Always reports `0` Power and `0` Voltage

Both have firmware `0x02040045`.
I tried resetting and re-pairing. But it did not solve the issue...

**Comment by claymen** [comment]
Mine all report their instant power and voltage, just not all of them report the total consumed. Though weirdly one of the broken ones now is reporting it, and is definitely showing usage that matches the 20w or so of load that device generally uses.

**Comment by notDavid** [comment]
I simply returned the broken ones to Ikea, and got a new one... 🤷🏼‍♂️

**Comment by LeoeLeoeL** [comment]
I mitigated the issue using a helper in Home Assistant. It calculates KWh using the power entity

**Comment by sander85** [comment]
I found something interesting and quite bogus under the Reporting tab. Default values for Min rep change are 50 for multiple values and Max rep interval is 65000, when i lowered these values the plug started reporting pretty well. Didn't know about this configuration. Actually my mind is blown and I'm now checking many other devices I've had problems with. Maybe these can be tweaked the same way..

**Comment by LeoeLeoeL** [comment]
I tried many things in Reporting tab but, in my case, it didn't solve the issue

**Comment by Koenkk** [comment]
You can try force reading the power value via the frontend:

<img width="1169" height="490" alt="Image" src="https://github.com/user-attachments/assets/5ce9ea00-0ec4-441a-8730-3024196c7c54" />

If it logs `zhc:tz: Read result of 'haElectricalMeasurement': {"activePower":0}` when under load it means an issue with the plug (and thus it cannot be solved from z2m)

**Comment by LeoeLeoeL** [comment]
The issue is in currentSummDelivered.
I never had problems with activePower; It reports Watts correctly.

**Comment by Koenkk** [comment]
Can you try to read the currentSummDelivered? Its available in the seMetering cluster

**Comment by claymen** [comment]
> Can you try to read the currentSummDelivered? Its available in the seMetering cluster

Let me know if this was not correct

<img width="853" height="423" alt="Image" src="https://github.com/user-attachments/assets/3745f55d-fe1e-46e6-b7c5-d4f4749514b9" />

This one is a non-working plug
[30/09/2025, 8:24:44 am] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/SW-Voron', payload '{"current":3.257,"device":{"applicationVersion":2,"dateCode":"20240801","friendlyName":"SW-Voron","hardwareVersion":1,"ieeeAddr":"0xf074bffffee7bfcf","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"E2206","networkAddress":207,"powerSource":"Mains (single phase)","softwareBuildID":"2.4.45","stackVersion":114,"type":"Router","zclVersion":8},"energy":0,"identify":null,"last_seen":"2025-09-30T08:24:43+08:00","linkquality":87,"power":781.4,"power_on_behavior":"previous","state":"ON","update":{"installed_version":33816645,"latest_version":33816645,"state":"idle"},"voltage":239.5}'

This is from one of the working ones
[30/09/2025, 8:25:39 am] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/SW-ServerRack', payload '{"current":1.447,"device":{"applicationVersion":2,"dateCode":"20240801","friendlyName":"SW-ServerRack","hardwareVersion":1,"ieeeAddr":"0xf074bffffee82dc9","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"E2206","networkAddress":33538,"powerSource":"Mains (single phase)","softwareBuildID":"2.4.45","stackVersion":114,"type":"Router","zclVersion":8},"energy":710.246,"identify":null,"last_seen":"2025-09-30T08:25:37+08:00","linkquality":163,"power":314,"power_on_behavior":"on","state":"ON","update":{"installed_version":33816645,"latest_version":33816645,"state":"idle"},"voltage":238.9}'

Both are under load, as the power figure seems to be accurate comparing against my main power meter monitoring (e.g. switching it off and checking the difference). Randomly I have had the non-working one start reporting a total sum, but it's back to not reporting again.

Is it worth updating my zStack firmware as a test? Currently still on Revision: 20230507

Let me know if there's any other debug/diags you'd like.

**Comment by Koenkk** [comment]
I forgot to ask to debug log when doing the read.

> See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by claymen** [comment]
> I forgot to ask to debug log when doing the read.
> 
> > See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

I have the following already set.
  log_level: debug

Is there anything in the log I need to mask out, it's going to be quite noisy, or would you like me to send to you directly?

**Comment by Koenkk** [comment]
Just send it, I will filter

**Comment by LeoeLeoeL** [comment]
Excuse me if i'm so straightforward but,there should be a priority to fix the problem of spikes of energy metering than this one.
Because, when you fix the issue of energy=0 then the people meet the other one.

**Comment by claymen** [comment]
> Just send it, I will filter

Apologies for the large log, I tried to cover a few examples off

Working examples
- SW-ServerRack
- SW-Fridge

Broken examples
- SW-Voron
- SW-CR10sPro

I ran the read of currentSummDelivered 3-4 times on each to try and give a reference to working vs non-working if that helps to identify it. I also started from a clean log, and a fresh boot of zigbee2mqtt.

[log.log](https://github.com/user-attachments/files/22651215/log.log)

**Comment by Koenkk** [comment]
@claymen I checked the log but the device really reports `energy: 0`:

```
[2025-10-02 08:55:54] debug: 	z2m: Received Zigbee message from 'SW-Voron', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":0}' from endpoint 1 with groupID 0
```

Given the other one works, could it be that `SW-Voron` is just broken?

**Comment by claymen** [comment]
> [@claymen](https://github.com/claymen) I checked the log but the device really reports `energy: 0`:
> 
> ```
> [2025-10-02 08:55:54] debug: 	z2m: Received Zigbee message from 'SW-Voron', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":0}' from endpoint 1 with groupID 0
> ```
> 
> Given the other one works, could it be that `SW-Voron` is just broken?

Potentially, or IKEA need to fix something firmware wise, trying to figure out why sometimes it did work. Is there a way to force an OTA update to the same firmware? The classic, reset everything and re-flash the firmware?

**Comment by claymen** [comment]
> [@claymen](https://github.com/claymen) I checked the log but the device really reports `energy: 0`:
> 
> ```
> [2025-10-02 08:55:54] debug: 	z2m: Received Zigbee message from 'SW-Voron', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":0}' from endpoint 1 with groupID 0
> ```
> 
> Given the other one works, could it be that `SW-Voron` is just broken?

Though to throw a spanner in the works, I just removed two of the ones having issues SW-Voron and SW-CR10sPro, reconnected my old tubeszb-cc2652-poe via ZHA and they are now reporting. Basically have both of the offending plugs plugged into each other and to a light I know draws about 45w

Interesting the wildly different voltage readings... though

<img width="330" height="330" alt="Image" src="https://github.com/user-attachments/assets/20dfe847-eae9-434d-b8e0-f8ed935c4e95" />

<img width="329" height="330" alt="Image" src="https://github.com/user-attachments/assets/94ae60fe-235a-4913-aa72-0f2fc955b63d" />

But for testing, I have 4 on zigbee2mqtt (first 4) and last 2 are on ZHA

<img width="945" height="448" alt="Image" src="https://github.com/user-attachments/assets/a092568f-4648-4b4a-90b5-bbc745593ef2" />

And the voltage readings across them are all different, 3 of them 250v~ the other 3 about 240v~

But all are recording total usage, and wattages are within margin of error. In any case, I'll leave them running for the day, check the totals and then re-bind the now working ones back to zigbee2mqtt and see what happens.

**Comment by claymen** [comment]
It's been a few hours now and both "broken" plugs are definitely showing energy usage on ZHA

<img width="685" height="516" alt="Image" src="https://github.com/user-attachments/assets/9c6b5d88-cc76-40bb-a33a-d881c87ebd31" />

<img width="686" height="550" alt="Image" src="https://github.com/user-attachments/assets/00fd9264-641a-436c-8216-e0f4ec31f8f2" />

I've rolled these two back to Zigbee2MQTT and testing now with a little more load to bump the numbers up faster.

<img width="1618" height="615" alt="Image" src="https://github.com/user-attachments/assets/7c19ad90-32c6-4123-9fc1-ea6371b21cb2" />

For reference the ZHA coordinator is Z-Stack 20211217 vs 20230507 on the other.

**Comment by claymen** [comment]
Quick edit as I screwed up some of my testing. When I have re-added them to zigbee2mqtt I've not changed the polling intervals, so I ran a manual poll and now seeing some data. I will continue with it as is for now which is to say I now have two zigbee2mqtt instances with one of the non-working plugs on each.

We have
tubeszb-cc2652-poe - zigbee2mqtt - Revision: 20250321 (now updated)
usb-cc2652 - zigbee2mqtt - Revision: 20230507

Both non-working devices were removed, then re-joined one to each. Current status, both are now working. Possibly just removing then re-adding was the fix?

<img width="1615" height="825" alt="Image" src="https://github.com/user-attachments/assets/a198d3d3-3c64-442e-9509-b5ca23dbeb47" />

**Comment by claymen** [comment]
So at this point, I went around to all the devices not reporting, removed from zigbee2mqtt, powered them off, powered back on, re-joined and so far are reporting fine. I'm a bit at a loss other than there's something a bit wonky in the IKEA firmware. I've done the zstack upgrades as a bit of maintenance anyway, and all seems well. Will continue to monitor.

**Comment by markheloking** [comment]
I'm also having the issue where one of my Inspelnings suddenly is not reporting cumulative energy anymore. Weird thing is that it just suddenly happened one day where it was working perfectly fine before.

Please let me know if I can help with testing. Haven't tried repairing it or anything yet as this one is annoyingly out of reach (need to move a closet and a fridge out of the way for it)

**Comment by claymen** [comment]
> I'm also having the issue where one of my Inspelnings suddenly is not reporting cumulative energy anymore. Weird thing is that it just suddenly happened one day where it was working perfectly fine before.
> 
> Please let me know if I can help with testing. Haven't tried repairing it or anything yet as this one is annoyingly out of reach (need to move a closet and a fridge out of the way for it)

Yeah it's random, ne that was working has now decided not to work again. Yet the other non-working one is still working. Go figure. There's something funky with the firmware.

<img width="1469" height="414" alt="Image" src="https://github.com/user-attachments/assets/ffa718d9-a3a4-4c6c-bdf6-c8c4610a0c76" />

**Comment by martinroger** [comment]
Just bought a fresh batch of Inspelnings. All of them seem to work OK except one, that is not exposing power nor voltage, but is exposing current correctly, even under high load. All of this is under Z2M and latest firmware for the plug itself.

Tried all combinations of pairing/unpairing/resetting/reconfiguring and even fiddled with the reporting intervals, alas to no success. 
Was any solution found ? I guess it's also not possible to force a "reflash" to the same FW version, is it ?

**Comment by tompointexe** [comment]
> Just bought a fresh batch of Inspelnings. All of them seem to work OK except one, that is not exposing power nor voltage, but is exposing current correctly, even under high load. All of this is under Z2M and latest firmware for the plug itself.
> 
Hi,
That's exactly the issue I'm facing, returns Amps currently, but not voltage so no Watts consumed
Feels like they will just become simple smart plugs with no energy monitoring
Thanks

**Comment by claymen** [comment]
It's such a weird issue, as I've had plugs which didn't work for some time, suddenly then start working. Trying to narrow down any changes, and the only change was introducing a few Shelly EM Mini Gen4's in Zigbee mode which I noticed seem to get a much higher preference for devices to connect to. With that said, if you are using Home Assistant you can workaround the issue with a helper, it's not perfect but at least because my wattage was always accurate, this gets close enough for general power metering.

**Comment by martinroger** [comment]
> It's such a weird issue, as I've had plugs which didn't work for some time, suddenly then start working. Trying to narrow down any changes, and the only change was introducing a few Shelly EM Mini Gen4's in Zigbee mode which I noticed seem to get a much higher preference for devices to connect to. With that said, if you are using Home Assistant you can workaround the issue with a helper, it's not perfect but at least because my wattage was always accurate, this gets close enough for general power metering.

You always had wattage but not the other reports? In my case I get no physical measurements but that one plug works fine otherwise...

**Comment by claymen** [comment]
> You always had wattage but not the other reports? In my case I get no physical measurements but that one plug works fine otherwise...

My issue has always been that all the stats except the accumulated power consumption worked. So I had wattage, amps, volts etc, but kwhr would just never increase.
