### ISSUE TITLE
EnOcean PTM 215Z are not working under 2.5.1.1

### ISSUE THREAD

**Issue by GunterAv** [Koenkk/zigbee2mqtt#27888]
### What happened?

I have 11 EnOcean PTM 215Z in my home.
With Version 2.4-0-1 all works fine.

under 2.51 AND 2.5.1.1 no EnOcean PTM 215Z is working

### What did you expect to happen?

that they work switches

### How to reproduce it (minimal and precise)

install Version 2.5.1.1

### Zigbee2MQTT version

2.5.1.1

### Adapter firmware version

26780700

### Adapter

Conbee II

### Setup

...

### Debug log

...

**Comment by tpftpf** [comment]
I can not confirm this problem.
My 13 PTM 216Z still work without a problem on 2.5.1

**Comment by manup** [comment]
Can you please share a debug log?

I have tested with a Friends of Hue Dimmer (which uses a similar ZGP module) this one works.
Hopefully the logs show if there are problems parsing the incoming messages.

**Comment by tpftpf** [comment]
I have PTM 216Z not PTM 215Z, my bad.
Here is the log of a button press/release:

> info 2025-07-03 09:30:32z2m:mqtt: MQTT publish: topic 'zigbee2mqtt_east/bedroom_printer_enocean_switch', payload '{"action":"press_2_and_4","last_seen":1751527833275,"linkquality":215}'
info 2025-07-03 09:30:32z2m:mqtt: MQTT publish: topic 'zigbee2mqtt_east/bedroom_printer_enocean_switch', payload '{"action":"release","last_seen":1751527833472,"linkquality":215}'

**Comment by manup** [comment]
This looks to be working?
Sorry I meant the log output for the PTM 215Z switches that don't work.

**Comment by GunterAv** [comment]
Hello,

I see all EnOcean switches in Zigbee2MQTT, but when I press a button there is no feedback.
That's why I don't have a debug log.

Re-learning is also not possible. The switch is not recognized.

I have now reactivated my HUE Bridge, where I was able to add a new switch and assign it in HA.

Best regards
Gunter

**Comment by tim-dalkiewicz** [comment]
I have the same problem.

After updating to 2.5.1 only these [PTM_215Z](https://www.zigbee2mqtt.io/devices/PTM_215Z.html) aren't working anymore. Zigbee2Mqtt said its connected, but I don't see any loggings or (error) messages.
I have 6 Switches... none of them is working.

Other Switches like [TH-S04D](https://www.zigbee2mqtt.io/devices/TH-S04D.html) or [Hue dimmer switch](https://www.zigbee2mqtt.io/devices/324131092621.html) are working

My setup:
Raspi 4: HAS OS, Home Assistant
Core: 2025.7.0
Supervisor: 2025.06.2
Operating System: 15.2

Conbee Stick II

**Comment by manup** [comment]
I'm currently looking into it, my Friends of Hue switch which seems to work also says it is a "PTM 215Z" but it might be different from other EnOcen modules and use different commands.

![Image](https://github.com/user-attachments/assets/e42f6d45-2b81-4697-9325-92d416c9b4a2)

In my logs I see that there are a few commands skipped while parsing with an error.
I'll make a PR to fix these to parse any ZGP command.

Still wonder what is the difference between ZGP handling in old vs new adapter since ZGP code wasn't changed. Might be a side effect.

**Comment by manup** [comment]
Note my `configuration.yaml` has enabled debug log level which yields more details:

```
advanced:
  log_level: debug
```

**Comment by KapUttyy** [comment]
I had the same issue. Rolled back to 2.4.0-1 in HA with Conbee II and it is working again.

Nevertheless I had to restore also the configuration.yaml and the database.db files from the Z2Ms homeassistant configuration folder.
After the Upgrade to 2.5.0-1 or 2.5.1-1 the device is displayed as online, but it does not receive anymore updates. Unfortunately I do not have a debug log of the device after the upgrade and because of the Womans Acceptance Factor, I currently don't want to upgrade again.

Nevertheless I have a debug log of a button press with the working 2.4.0-1 version.

```
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP_DATA_INDICATION - src id: 0x174eb0f cmd id: 0x12 frameCounter: 0x4cad
[2025-07-03 15:05:43] debug: 	zh:controller:greenpower: [UNHANDLED_CMD/PASSTHROUGH] command=0x12 srcID=24439567 gpp=NO
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=33, address=60175, groupID=2948, endpoint=242, destinationEndpoint=242, wasBroadcast=true, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":127,"commandIdentifier":0},"payload":{"options":0,"srcID":24439567,"frameCounter":19629,"commandID":18,"payloadSize":0,"commandFrame":{}},"command":{"ID":0,"parameters":[{"name":"options","type":25},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009,"conditions":[{"type":"bitMaskSet","param":"options","mask":192,"reversed":true}]},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGpdLink","type":24,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}}
[2025-07-03 15:05:43] debug: 	z2m: Received Zigbee message from 'FOH-Lichtschalter Wohnzimmer', type 'commandNotification', cluster 'greenPower', data '{"commandFrame":{},"commandID":18,"frameCounter":19629,"options":0,"payloadSize":0,"srcID":24439567}' from endpoint 242 with groupID 2948
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer', payload '{"action":"press_4","last_seen":"2025-07-03T13:05:43.365Z","linkquality":255}'
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer/action', payload 'press_4'
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/Lichtschalter Esszimmerlampe/set' with data 'OFF'
[2025-07-03 15:05:43] debug: 	z2m: Publishing 'set' 'state' to 'Lichtschalter Esszimmerlampe'
[2025-07-03 15:05:43] debug: 	zh:controller:endpoint: ZCL command 0x30fb10fffe756788/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false})
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: DATA_REQUEST - destAddr: 0xa59f EP:1 SeqNr. 127 request id: 221
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_REQUEST RESPONSE - request id: 221 status: 0
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_REQUEST RESPONSE - request id: 221 status: 0
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10100110
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10100110
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: query aps data confirm
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: DATA_CONFIRM - sending data state request - SeqNr. 128
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_CONFIRM RESPONSE - destAddr: 0xa59f request id: 221 confirm status: 0
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz: sendZclFrameToEndpoint - message send with transSeq Nr.: 52
[2025-07-03 15:05:43] debug: 	zh:deconz: false, false, false, 10000
[2025-07-03 15:05:43] debug: 	zh:deconz: resolve request (52)
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10101010
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10101010
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: query aps data indication
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: DATA_INDICATION - sending read data request - SeqNr. 129
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_INDICATION RESPONSE - seqNr. 129 srcAddr: 0xeb0f destAddr: 0xdd09 profile id: 0xa1e0 cluster id: 0x21 lqi: 255
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: response payload: 112000a0540feb7401ad4c0000120092c6d3
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:controller:greenpower: [UNHANDLED_CMD/PASSTHROUGH] command=0x12 srcID=24439567 gpp=50834 rssi=19 linkQuality=Excellent
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_INDICATION RESPONSE - seqNr. 129 srcAddr: 0xeb0f destAddr: 0xdd09 profile id: 0xa1e0 cluster id: 0x21 lqi: 255
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: response payload: 112000a0540feb7401ad4c0000120092c6d3
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:controller:greenpower: [UNHANDLED_CMD/PASSTHROUGH] command=0x12 srcID=24439567 gpp=50834 rssi=19 linkQuality=Excellent
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=33, address=60175, groupID=56585, endpoint=242, destinationEndpoint=0, wasBroadcast=true, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":32,"commandIdentifier":0},"payload":{"options":21664,"srcID":24439567,"frameCounter":19629,"commandID":18,"payloadSize":0,"commandFrame":{},"gppNwkAddr":50834,"gppGpdLink":211},"command":{"ID":0,"parameters":[{"name":"options","type":25},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009,"conditions":[{"type":"bitMaskSet","param":"options","mask":192,"reversed":true}]},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGpdLink","type":24,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}}
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=33, address=60175, groupID=56585, endpoint=242, destinationEndpoint=0, wasBroadcast=true, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":32,"commandIdentifier":0},"payload":{"options":21664,"srcID":24439567,"frameCounter":19629,"commandID":18,"payloadSize":0,"commandFrame":{},"gppNwkAddr":50834,"gppGpdLink":211},"command":{"ID":0,"parameters":[{"name":"options","type":25},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009,"conditions":[{"type":"bitMaskSet","param":"options","mask":192,"reversed":true}]},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGpdLink","type":24,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}}
[2025-07-03 15:05:43] debug: 	z2m: Received Zigbee message from 'FOH-Lichtschalter Wohnzimmer', type 'commandNotification', cluster 'greenPower', data '{"commandFrame":{},"commandID":18,"frameCounter":19629,"gppGpdLink":211,"gppNwkAddr":50834,"options":21664,"payloadSize":0,"srcID":24439567}' from endpoint 242 with groupID 56585
[2025-07-03 15:05:43] debug: 	z2m: Received Zigbee message from 'FOH-Lichtschalter Wohnzimmer', type 'commandNotification', cluster 'greenPower', data '{"commandFrame":{},"commandID":18,"frameCounter":19629,"gppGpdLink":211,"gppNwkAddr":50834,"options":21664,"payloadSize":0,"srcID":24439567}' from endpoint 242 with groupID 56585
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer', payload '{"last_seen":"2025-07-03T13:05:43.416Z","linkquality":255}'
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer', payload '{"last_seen":"2025-07-03T13:05:43.416Z","linkquality":255}'
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP_DATA_INDICATION - src id: 0x174eb0f cmd id: 0x16 frameCounter: 0x4cae
[2025-07-03 15:05:43] debug: 	zh:controller:greenpower: [UNHANDLED_CMD/PASSTHROUGH] command=0x16 srcID=24439567 gpp=NO
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=33, address=60175, groupID=2948, endpoint=242, destinationEndpoint=242, wasBroadcast=true, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":130,"commandIdentifier":0},"payload":{"options":0,"srcID":24439567,"frameCounter":19630,"commandID":22,"payloadSize":0,"commandFrame":{}},"command":{"ID":0,"parameters":[{"name":"options","type":25},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009,"conditions":[{"type":"bitMaskSet","param":"options","mask":192,"reversed":true}]},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGpdLink","type":24,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}}
[2025-07-03 15:05:43] debug: 	z2m: Received Zigbee message from 'FOH-Lichtschalter Wohnzimmer', type 'commandNotification', cluster 'greenPower', data '{"commandFrame":{},"commandID":22,"frameCounter":19630,"options":0,"payloadSize":0,"srcID":24439567}' from endpoint 242 with groupID 2948
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer', payload '{"action":"release_4","last_seen":"2025-07-03T13:05:43.489Z","linkquality":255}'
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer/action', payload 'release_4'
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: GP data notification
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10101010
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10101010
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: query aps data indication
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: DATA_INDICATION - sending read data request - SeqNr. 130
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_INDICATION RESPONSE - seqNr. 130 srcAddr: 0xeb0f destAddr: 0xdd09 profile id: 0xa1e0 cluster id: 0x21 lqi: 255
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: response payload: 112100a0540feb7401ae4c0000160092c6d3
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:controller:greenpower: [UNHANDLED_CMD/PASSTHROUGH] command=0x16 srcID=24439567 gpp=50834 rssi=19 linkQuality=Excellent
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_INDICATION RESPONSE - seqNr. 130 srcAddr: 0xeb0f destAddr: 0xdd09 profile id: 0xa1e0 cluster id: 0x21 lqi: 255
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: response payload: 112100a0540feb7401ae4c0000160092c6d3
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:controller:greenpower: [UNHANDLED_CMD/PASSTHROUGH] command=0x16 srcID=24439567 gpp=50834 rssi=19 linkQuality=Excellent
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=33, address=60175, groupID=56585, endpoint=242, destinationEndpoint=0, wasBroadcast=true, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":33,"commandIdentifier":0},"payload":{"options":21664,"srcID":24439567,"frameCounter":19630,"commandID":22,"payloadSize":0,"commandFrame":{},"gppNwkAddr":50834,"gppGpdLink":211},"command":{"ID":0,"parameters":[{"name":"options","type":25},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009,"conditions":[{"type":"bitMaskSet","param":"options","mask":192,"reversed":true}]},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGpdLink","type":24,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}}
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=33, address=60175, groupID=56585, endpoint=242, destinationEndpoint=0, wasBroadcast=true, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":33,"commandIdentifier":0},"payload":{"options":21664,"srcID":24439567,"frameCounter":19630,"commandID":22,"payloadSize":0,"commandFrame":{},"gppNwkAddr":50834,"gppGpdLink":211},"command":{"ID":0,"parameters":[{"name":"options","type":25},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009,"conditions":[{"type":"bitMaskSet","param":"options","mask":192,"reversed":true}]},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGpdLink","type":24,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}}
[2025-07-03 15:05:43] debug: 	z2m: Received Zigbee message from 'FOH-Lichtschalter Wohnzimmer', type 'commandNotification', cluster 'greenPower', data '{"commandFrame":{},"commandID":22,"frameCounter":19630,"gppGpdLink":211,"gppNwkAddr":50834,"options":21664,"payloadSize":0,"srcID":24439567}' from endpoint 242 with groupID 56585
[2025-07-03 15:05:43] debug: 	z2m: Received Zigbee message from 'FOH-Lichtschalter Wohnzimmer', type 'commandNotification', cluster 'greenPower', data '{"commandFrame":{},"commandID":22,"frameCounter":19630,"gppGpdLink":211,"gppNwkAddr":50834,"options":21664,"payloadSize":0,"srcID":24439567}' from endpoint 242 with groupID 56585
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer', payload '{"last_seen":"2025-07-03T13:05:43.533Z","linkquality":255}'
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/FOH-Lichtschalter Wohnzimmer', payload '{"last_seen":"2025-07-03T13:05:43.533Z","linkquality":255}'
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10101010
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DEVICE_STATE changed: 10101010
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: query aps data indication
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: DATA_INDICATION - sending read data request - SeqNr. 131
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_INDICATION RESPONSE - seqNr. 131 srcAddr: 0xa59f destAddr: 0x0 profile id: 0x104 cluster id: 0x6 lqi: 255
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: response payload: 18340b0000
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=6, address=42399, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=255, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":52,"commandIdentifier":11},"payload":{"cmdId":0,"statusCode":0},"command":{"ID":11,"name":"defaultRsp","parameters":[{"name":"cmdId","type":32},{"name":"statusCode","type":32}]}}
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Lichtschalter Esszimmerlampe', payload '{"last_seen":"2025-07-03T13:05:43.786Z","linkquality":255,"power_on_behavior":"off","state":"OFF","update":{"installed_version":4110,"latest_version":4110,"state":"idle"},"update_available":false}'
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: DATA_INDICATION RESPONSE - seqNr. 131 srcAddr: 0xa59f destAddr: 0x0 profile id: 0x104 cluster id: 0x6 lqi: 255
[2025-07-03 15:05:43] debug: 	zh:deconz:frameparser: response payload: 18340b0000
[2025-07-03 15:05:43] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
[2025-07-03 15:05:43] debug: 	zh:controller: Received payload: clusterID=6, address=42399, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=255, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":52,"commandIdentifier":11},"payload":{"cmdId":0,"statusCode":0},"command":{"ID":11,"name":"defaultRsp","parameters":[{"name":"cmdId","type":32},{"name":"statusCode","type":32}]}}
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Lichtschalter Esszimmerlampe', payload '{"last_seen":"2025-07-03T13:05:43.786Z","linkquality":255,"power_on_behavior":"off","state":"OFF","update":{"installed_version":4110,"latest_version":4110,"state":"idle"},"update_available":false}'
[2025-07-03 15:05:43] debug: 	zh:deconz: response received (52)
[2025-07-03 15:05:43] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Lichtschalter Esszimmerlampe', payload '{"last_seen":"2025-07-03T13:05:43.786Z","linkquality":255,"power_on_behavior":"off","state":"OFF","update":{"installed_version":4110,"latest_version":4110,"state":"idle"},"update_available":false}'
```

**Comment by Nerivec** [comment]
@tim-dalkiewicz can you provide a `debug` log of trying to press buttons (even if you see nothing, so we have some context)? And also of trying to re-pair one of the switches (make sure to confirm the channel at the end BEFORE pressing any other button - see [docs](https://www.zigbee2mqtt.io/devices/PTM_215Z.html#pairing))?

**Comment by phil-schneider** [comment]
> I had the same issue. Rolled back to 2.4.0-1 in HA with Conbee II and it is working again.
> 
> Nevertheless I had to restore also the configuration.yaml and the database.db files from the Z2Ms homeassistant configuration folder. After the Upgrade to 2.5.0-1 or 2.5.1-1 the device is displayed as online, but it does not receive anymore updates. Unfortunately I do not have a debug log of the device after the upgrade and because of the Womans Acceptance Factor, I currently don't want to upgrade again.
> 

@KapUttyy How did you do that?
I tried to rollback to 2.4.0, but it didn't work.  I think its because of the missions configuration and DB.

**Comment by tim-dalkiewicz** [comment]
> [@tim-dalkiewicz](https://github.com/tim-dalkiewicz) can you provide a `debug` log of trying to press buttons (even if you see nothing, so we have some context)? And also of trying to re-pair one of the switches (make sure to confirm the channel at the end BEFORE pressing any other button - see [docs](https://www.zigbee2mqtt.io/devices/PTM_215Z.html#pairing))?

Logfile from today and my configuration.
All PTM 215Z Topics starting with `button.buschjaeger.4er.`
I will do the re-pairing, later.

[log.txt](https://github.com/user-attachments/files/21046086/log.txt)

[configuration.txt](https://github.com/user-attachments/files/21046116/configuration.txt)

**Comment by Nerivec** [comment]
@manup looks like a range error somewhere:
```
[2025-07-03 14:27:11] debug: 	zh:deconz:frameparser: GP_DATA_INDICATION - src id: 0x1766623 cmd id: 0x64 frameCounter: 0x323
[2025-07-03 14:27:11] debug: 	zh:deconz:frameparser: GREEN_POWER INDICATION - RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received -2
[2025-07-03 14:27:11] debug: 	zh:deconz:frameparser: GP_DATA_INDICATION - src id: 0x1766623 cmd id: 0x65 frameCounter: 0x324
[2025-07-03 14:27:11] debug: 	zh:deconz:frameparser: GREEN_POWER INDICATION - RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received -2
```
https://github.com/Koenkk/zigbee-herdsman/blob/a27fe889c79bd50e6eb84f4961320aa3e25c02be/src/adapter/deconz/driver/frameParser.ts#L502

**Comment by manup** [comment]
Yes it is caused by an out of range access into an array.

I put up a PR to fix it soon.

Oddly while the ZGP parsing code didn't change, the lower level received buffer was refactored in the new adapter to not yield over sized buffers to the parser — e.g. if the firmware sends a 64 byte buffer don't push a 128 byte buffer to the parser.

The ZGP parser in old and new adapter is a bit flaky and calculates some offsets under wrong assumptions with fixed magic numbers. This is what the PR will fix.

**Comment by Nerivec** [comment]
That error is specific to trying to `writeXYZ` with a value out of the range of _XYZ_ (here `-2` to `UInt8`).
Based on the logs, it's the `emit` that throws, so, looks like it's the GPD header in `checkReceivedGreenPowerIndication` that can't be computed properly (one of the `writeUInt8` is being given `-2` as value, so, `commandFrameSize` - if `view.byteLength === 22` that would put `commandFrameSize` at `-2`).
https://github.com/Koenkk/zigbee-herdsman/blob/a27fe889c79bd50e6eb84f4961320aa3e25c02be/src/adapter/deconz/adapter/deconzAdapter.ts#L677-L686

**Comment by KapUttyy** [comment]
> [@KapUttyy](https://github.com/KapUttyy) How did you do that? I tried to rollback to 2.4.0, but it didn't work. I think its because of the missions configuration and DB.

I downloaded my Full Daily Backup from before updating to 2.5.0-1.
Then I stopped Z2M and rolled back to the Z2M AddOn from the Full Daily Backup mentioned earlier. From the downloaded package I took the /homeassistant/zigbee2mqtt folder and replaced the configuration.yaml and the database.db file.
After that I restarted Z2M AddOn which then came up with a working FoH Switch.

**Comment by KapUttyy** [comment]
So as I can see the issue should be fixed with the already released zigbee-herdsman version, right?
Using Z2M as a homeassistant AddOn, I still have to wait for a new Z2M version as herdsman is part of the AddOn, correct?

**Comment by manup** [comment]
Yes if I understand it correctly the fixes are now in the `dev` channel. For the AddOn this is the `Edge` version of it (see: https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#home-assistant-addon).

**Comment by spatu** [comment]
Just to add a data point: my three PTM215Z (Friends of Hue) are working fine with Zigbee2MQTT 2.5.1. 

Details:
- PTM215Z model: GreenPower_2
- Zigbee2MQTT version: 2.5.1
- zigbee-herdsman-converters: 23.69.0
- zigbee-herdsman: 4.3.1
- Coordinator: Z-Stack 3.x.0 (Texas Instruments), firmware 20240710
- Frontend: 0.9.16
- GreenPower message events are received in the logs and automations work as expected.

My PTM215Z was paired some time ago (not after 2.5.1 update). Could be related to pairing vs upgrade?

Let me know if you want debug logs or GreenPower payloads for comparison.

**Comment by KapUttyy** [comment]
The issue is related only to Conbee Sticks with the Deconz driver.

**Comment by tzitzaki** [comment]
I've updated to 2.5.1-1
The switches still do not work - do I have to repair?

**Comment by manup** [comment]
> I've updated to 2.5.1-1 The switches still do not work - do I have to repair?

No, the fix is in a version after that. Currently in dev channel. See https://github.com/Koenkk/zigbee2mqtt/issues/27888#issuecomment-3047878732

**Comment by RayLio42** [comment]
Hi, thanks for the fix, but when will we see it in prod release?
The wife acceptance factor is under a stress test right now as no wall switch works anymore…

**Comment by tzitzaki** [comment]
Guess based on prior releases: starting of next month.

There is a section in the readme how to switch to the edge version of the plugin relatively hassle-free.
Linked above.

And as always, stick to the etiquette; no asking for ETA 😘

**Comment by TacoV** [comment]
Waited out the update, it was available today. Can confirm: the switches directly worked again 🚀
