### ISSUE TITLE
2.5.1-1 : impossible to permit join

### ISSUE THREAD

**Issue by phklrz** [Koenkk/zigbee2mqtt#27902]
### What happened?

After upgrading to 2.5.1-1, when trying to toggle permit join the following error appears:
`z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Failed APS-DATA.request with confirm status: unknown (0xa6)'`

### What did you expect to happen?

Permit join allowed

### Zigbee2MQTT version

2.5.1-1

### Adapter firmware version

0x26580700

### Adapter

Conbee II

### Setup

Add-on on Home Assistant on home assistant green

**Comment by manup** [comment]
I can't re-create the error also with old firmware version 0x26580700 it works here when pressing the "All" join button.

```
[2025-07-04 17:38:14] debug: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"we35h-1"}'
[2025-07-04 17:38:14] info: 	z2m: Zigbee: allowing new devices to join.
[2025-07-04 17:38:14] debug: 	zh:deconz:driver: Send write parameter request from queue. seq: 237 parameter: STK_PERMIT_JOIN
[2025-07-04 17:38:14] debug: 	zh:deconz:frameparser: Write parameter response parameter: STK_PERMIT_JOIN, status: Success
[2025-07-04 17:38:14] debug: 	zh:deconz: Permit joining on coordinator for 254 sec.
[2025-07-04 17:38:14] debug: 	zh:deconz:driver: Request APS-DATA.request: dest: 0xfffc EP:0 seq: 238 requestId: 1
[2025-07-04 17:38:14] debug: 	zh:deconz:frameparser: Response APS-DATA.request APS request id: 1 status: Success
[2025-07-04 17:38:15] debug: 	zh:deconz:driver: Request APS-DATA.confirm seq: 246
[2025-07-04 17:38:15] debug: 	zh:deconz:frameparser: APS-DATA.confirm  destAddr: 0xfffc APS request id: 1 confirm status: Success 0x00
[2025-07-04 17:38:15] debug: 	zh:deconz: zclFrame to all - 242
[2025-07-04 17:38:15] debug: 	zh:deconz: sendZclFrameToAll - message send
[2025-07-04 17:38:15] debug: 	zh:deconz:driver: Request APS-DATA.request: dest: 0xfffd EP:242 seq: 247 requestId: 2
[2025-07-04 17:38:15] debug: 	zh:deconz:frameparser: Response APS-DATA.request APS request id: 2 status: Success
[2025-07-04 17:38:16] debug: 	zh:deconz:driver: Request APS-DATA.confirm seq: 1
[2025-07-04 17:38:16] debug: 	zh:deconz:frameparser: APS-DATA.confirm  destAddr: 0xfffd APS request id: 2 confirm status: Success 0x00
[2025-07-04 17:38:16] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254},"status":"ok","transaction":"we35h-1"}'
```

**Comment by manup** [comment]
Unicast Permit Join via specific router seems to works as well in my setup:

```
[2025-07-04 17:42:21] debug: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":"0x7cb03eaa00add426","time":254,"transaction":"we35h-5"}'
[2025-07-04 17:42:21] info: 	z2m: Zigbee: allowing new devices to join via 0x7cb03eaa00add426.
[2025-07-04 17:42:21] debug: 	zh:deconz:driver: Request APS-DATA.request: dest: 0x5674 EP:0 seq: 192 requestId: 10
[2025-07-04 17:42:21] debug: 	zh:deconz:frameparser: Response APS-DATA.request APS request id: 10 status: Success
[2025-07-04 17:42:21] debug: 	zh:deconz:driver: Request APS-DATA.confirm seq: 194
[2025-07-04 17:42:21] debug: 	zh:deconz:frameparser: APS-DATA.confirm  destAddr: 0x5674 APS request id: 10 confirm status: Success 0x00
[2025-07-04 17:42:21] debug: 	zh:deconz:driver: Request APS-DATA.indication seq: 195
[2025-07-04 17:42:21] debug: 	zh:deconz:frameparser: Response APS-DATA.indication seq: 195 srcAddr: 0x5674 destAddr: 0x0 profile id: 0x0000 cluster id: 0x8036 lqi: 255
[2025-07-04 17:42:21] debug: 	zh:controller: Received ZDO response: clusterId=PERMIT_JOINING_RESPONSE, status=SUCCESS, payload=undefined
[2025-07-04 17:42:21] debug: 	zh:deconz: ZCL request sent with transactionSequenceNumber.: 6
[2025-07-04 17:42:21] debug: 	zh:deconz: command.response: undefined, zcl.disableDefaultResponse: true, z2m.disableResponse: false, request.timeout: 10000
[2025-07-04 17:42:21] debug: 	zh:deconz:driver: Request APS-DATA.request: dest: 0x5674 EP:242 seq: 196 requestId: 11
[2025-07-04 17:42:21] debug: 	zh:deconz:frameparser: Response APS-DATA.request APS request id: 11 status: Success
[2025-07-04 17:42:21] debug: 	zh:deconz:driver: Request APS-DATA.confirm seq: 198
[2025-07-04 17:42:21] debug: 	zh:deconz:frameparser: APS-DATA.confirm  destAddr: 0x5674 APS request id: 11 confirm status: Success 0x00
[2025-07-04 17:42:21] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"device":"0x7cb03eaa00add426","time":254},"status":"ok","transaction":"we35h-5"}'
```

**Comment by jurgverhoeven** [comment]
I seem to be having the same issue after updating today.
`Error 2025-07-05 16:11:58z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Failed APS-DATA.request with confirm status: unknown (0xa6)'`
I'm using the same adapter version.

**Comment by Lachfrosch** [comment]
I had to do a fresh setup of home assistant today because I moved. Have the same error popping up, setup worked perfectly before.

**Comment by why83key** [comment]
Same here: with 2.4.0 adding new devices worked well. Then with 2.5.0:
`info: 	z2m: Zigbee: allowing new devices to join.`
`error: 	z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Failed APS-DATA.request with confirm status: unknown (0xa6)'`

Already known devices can be controlled, however.

Coordinator firmware version: 0x266b0700 (ConBee2)

**Comment by Rendeik** [comment]
I own a first series conbee, after updating to version 2.5.1 it no longer communicates with the devices and I can't even pair them again, I had to revert it to the previous version.

**Comment by manup** [comment]
Uff that was tricky, finally managed to re-create the 0xA6 error:

```
z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Failed APS-DATA.request with confirm status: unknown (0xa6)'
[2025-07-06 18:12:01] debug: 	z2m: Error: Failed APS-DATA.request with confirm status: unknown (0xa6)
    at parseApsConfirmResponse (/home/mpi/src/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:203:20)
    at parseFrame (/home/mpi/src/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:643:32)
    at processFrame (/home/mpi/src/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:589:53)
    at Driver.<anonymous> (/home/mpi/src/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:79:58)
    at Driver.emit (node:events:507:28)
    at Driver.onParsed (/home/mpi/src/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:1479:22)
    at Parser.emit (node:events:507:28)
    at Parser.onMessage (/home/mpi/src/zigbee-herdsman/src/adapter/deconz/driver/parser.ts:30:14)
    at slip.Decoder.p.handleEnd (/home/mpi/src/zigbee-herdsman/node_modules/.pnpm/slip@1.0.2/node_modules/slip/src/slip.js:189:18)
    at slip.Decoder.p.decode (/home/mpi/src/zigbee-herdsman/node_modules/.pnpm/slip@1.0.2/node_modules/slip/src/slip.js:143:32)
```

Working a fix.

**Comment by Lachfrosch** [comment]
Thanks for looking into this, looking forward to the fix 👍

**Comment by Koenkk** [comment]
Fixed by @manup, thanks!


Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by phklrz** [comment]
Thank you. Installed via zigbee2mqtt edge add_on in home assistant. Works without problem.

**Comment by why83key** [comment]
Yes, with edge it works again. Thanks for your work!

**Comment by RobSheppard1976** [comment]
I am seeing this also. It started a few days ago. I've uninstalled the current version and reinstalled, as well as the Edge version. I've been re-using the backed up YAML contents for the config, but still getting errors. 

2025-07-26 10:36:08z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'failed to send ZDO request seq: (1) Error: Failed APS-DATA.request with confirm status: MacNoChannelAccess (0xe1)'
2025-07-26 10:38:01z2m: EventBus error 'OnEvent/deviceAnnounce': ZCL command 0xbc026efffe0c777a/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (failed to send ZCL request (2) Error: Failed APS-DATA.request with confirm status: MacNoChannelAccess (0xe1))
2025-07-26 10:38:04zh:controller:device: Read response to 0xbc026efffe0c777a failed (ZCL command 0xbc026efffe0c777a/1 genTime.readRsp({"localTime":806841484}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":1,"reservedBits":0,"transactionSequenceNumber":80,"writeUndiv":false}) failed (failed to send ZCL request (80) Error: Failed APS-DATA.request with confirm status: MacNoChannelAccess (0xe1)))

**Comment by TLA020** [comment]
I have the same issue... No fix yet?

**Comment by iNETTechnik** [comment]
we too after upgrade conbee 3 to newest firmware

**Comment by hermanrobers** [comment]
Just wanted to let you know that in 2026, I still saw this error "Failed APS-DATA.request with confirm status: unknown (0xa6)"; on a Conbee II USB, tried many things, including restart of zigbee2mqtt, downgrade of zigbee2mqtt, search for new firmware of Conbee II (is not there), reboot of the computer. Ultimately only physically unplugging the USB stick (removing power) and plugging in again solved the problem. The issue seems to have started after a power-glitch that was short enough to reboot some of my computers/devices, but not all of them. The computer running z2m did a restart, but probably not fully poweroff the USB ports. May be helpful for others that see this message.
