### ISSUE TITLE
IKEA VALLHORN: `no_occupancy_since ` option doesn't persist when set from Z2M GUI

### ISSUE THREAD

**Issue by MilesTEG1** [Koenkk/zigbee2mqtt#28119]
### What happened?

I have a motion detector VALLHORN from IKEA:

<img width="1938" height="684" alt="Image" src="https://github.com/user-attachments/assets/792760a0-919c-4fba-9222-a9725e40e4ff" />

I want to put a value for `no_occupancy_since`, but when I put a value, it doesn't persist, and a refresh shows it's vanished.
I try to set `30`, or `30,60`.
I can't enter a [ or ], nor any space.

![Image](https://github.com/user-attachments/assets/2106f856-4a68-4c45-adc8-a643a0112d46)

### What did you expect to happen?

I expected that the setting persist.

### How to reproduce it (minimal and precise)

Appair the device, and try to set a value for `no_occupancy_since`.

### Zigbee2MQTT version

2.5.1

### Adapter firmware version

8.0.2 [GA]

### Adapter

SLZB-06M

### Setup

I'm running Z2M as an addon for HAOS on a Proxmox VM on an intel mini pc.
```shell
➜  ~ uname -a && cat /etc/issue.net
Linux a0d7b954-ssh 6.12.35-haos #1 SMP PREEMPT_DYNAMIC Wed Jul  9 14:17:59 UTC 2025 x86_64 Linux
cat: can't open '/etc/issue.net': No such file or directory
```

### Device `database.db` entry

```
{"id":126,"type":"EndDevice","ieeeAddr":"0x94a081fffe57bbf6","nwkAddr":22393,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"VALLHORN Wireless Motion Sensor","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":2128,"inClusterList":[0,1,3,32,2821,4096,64636,64641],"outClusterList":[3,4,6,25,4096],"clusters":{"genPollCtrl":{"attributes":{"checkinInterval":172800}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":172,"batteryVoltage":26}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x847127fffedfe3cd","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x847127fffedfe3cd","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":10},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":65000,"repChange":10}],"meta":{}},"2":{"profId":260,"epId":2,"devId":263,"inClusterList":[0,3,1030],"outClusterList":[3],"clusters":{"msOccupancySensing":{"attributes":{"occupancy":1}}},"binds":[{"cluster":1030,"type":"endpoint","deviceIeeeAddress":"0x847127fffedfe3cd","endpointID":1}],"configuredReportings":[{"cluster":1030,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"3":{"profId":260,"epId":3,"devId":262,"inClusterList":[0,3,1024],"outClusterList":[3],"clusters":{"msIlluminanceMeasurement":{"attributes":{"measuredValue":20253}}},"binds":[{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x847127fffedfe3cd","endpointID":1}],"configuredReportings":[{"cluster":1024,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":5}],"meta":{}}},"appVersion":1,"stackVersion":114,"hwVersion":1,"dateCode":"20240123","swBuildId":"1.0.64","zclVersion":8,"interviewCompleted":true,"interviewState":"SUCCESSFUL","meta":{"configured":332242049},"lastSeen":1753886288443,"checkinInterval":43200}
```

### Debug log

[log.log](https://github.com/user-attachments/files/21512242/log.log)

**Comment by Nerivec** [comment]
The `[x,y]` format is when sending raw payload. In the UI, each field corresponds to 1 item, so just one number per field is expected (due to field being number, it allows the comma character in this scenario, which is unfortunately a bit confusing with this field's description).

See above PR link for more details on the issue.

**Comment by MilesTEG1** [comment]
@Nerivec 
Thanks for look into it and do a fix.
I hope it'll be available in few hours in the dev branch.
And maybe in several days in the stable release of the month 😊

**Comment by Nerivec** [comment]
Should be available in latest-dev. Let us know how that works out.

**Comment by MilesTEG1** [comment]
Should I wait until tomorrow the stable release?
Because I have some manipulations to do I order to use latest dev in haos.

**Comment by MilesTEG1** [comment]
Hello @Nerivec 
Apologies for commenting here (I don't have permission to reopen the issue), but I'm currently testing Z2M-Edge on HAOS—likely the development branch—and the issue appears to persist.

![Image](https://github.com/user-attachments/assets/9d1af906-b485-49d8-a71d-3b2dcce1ea26)

**Comment by Nerivec** [comment]
It should be working (actually applied), but it appears to not be read back properly when you refresh, so it's empty.

Can you grab the `state.json` from Settings>Tools>Download state? I'll add a proper mock to test with from your device's data. _Some of these edge cases, there is a lack of data to test with._
Can you also confirm what you see in Z2M's `configuration.yaml` for that device once you've applied it?

**Comment by MilesTEG1** [comment]
> Can you grab the `state.json` from Settings>Tools>Download state? I'll add a proper mock to test with from your device's data. _Some of these edge cases, there is a lack of data to test with._

[state.json.zip](https://github.com/user-attachments/files/21555417/state.json.zip)




> Can you also confirm what you see in Z2M's `configuration.yaml` for that device once you've applied it?
I see this:
<img width="1310" height="590" alt="Image" src="https://github.com/user-attachments/assets/c0da3e1b-bd2f-4944-8838-5aac91cc27eb" />

```yaml
'0x94a081fffe57bbf6':
  friendly_name: Détecteur_Mouvement_Bureau
  no_occupancy_since:
    - null
    - null
  illuminance_raw: true
  illuminance_calibration: 200
```

I tried to remove the `no_occupancy_since` lines, refresh Z2M, redo the configuration of the values no_occupancy_since, and I still see those lines...
