### ISSUE TITLE
_TZE204_dapwryy7 stopped working on version 2.6.1

### ISSUE THREAD

**Issue by Wielebny666** [Koenkk/zigbee2mqtt#28464]
### What happened?

Hi,
after updating from version 2.6.0 to 2.6.1 the presence status does not change.
I changed it back to 2.6.0 and it works.

regards

### Zigbee2MQTT version

2.6.1

### Adapter firmware version

20250325

### Adapter

SLZB-06P7

### Setup

Docker container

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) tomorrow and in the next release which is every 1st of the month.

**Comment by Zylazy** [comment]
The dev branch solved the problem. Thank you!
Could it be related with the https://github.com/Koenkk/zigbee2mqtt/issues/27212 issue? Almost the same sensor, and almost the same problem. But those sensors are still not working well with the dev branch either!
