### ISSUE TITLE
Nous E12 - TS0601

### ISSUE THREAD

**Issue by lucaobermaier** [Koenkk/zigbee2mqtt#30372]
### What happened?

Hello

I just added one Nous E12 Monoxid sensor and get the following error:
`z2m: Exception while calling fromZigbee converter: Value 'false' is not allowed, expected one of OFF,ON} `

It also is showing permanently detection as "true".

Battery is always on 2%. Not more not less. Indicator on the device says full. 

### Zigbee2MQTT version

2.7.1-1

### Adapter firmware version

8.0.2

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2

### Setup

Homeassistant with Addon

**Comment by Koenkk** [comment]
could you provide the debug log of this error?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by lucaobermaier** [comment]
`[29.12.2025, 23:02:55] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Wohnzimmer CO Sensor', payload '{"battery":2,"carbon_monoxide":true,"carbon_monoxide_value":0,"checking_result":null,"device":{"applicationVersion":80,"dateCode":"","friendlyName":"Wohnzimmer CO Sensor","hardwareVersion":1,"ieeeAddr":"0xa4c138e3d813d2bc","manufacturerID":4417,"manufacturerName":"_TZE284_sonkaxrd","model":"E12","networkAddress":1559,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"fault":false,"lifecycle":true,"linkquality":116,"preheat":null,"self_checking":false}'`

`[29.12.2025, 23:05:08] z2m: Device 'Wohnzimmer CO Sensor' left the network
[29.12.2025, 23:05:08] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Wohnzimmer CO Sensor","ieee_address":"0xa4c138e3d813d2bc"},"type":"device_leave"}'
[29.12.2025, 23:05:12] z2m: Device 'Wohnzimmer CO Sensor' joined
[29.12.2025, 23:05:12] z2m: Starting interview of 'Wohnzimmer CO Sensor'
[29.12.2025, 23:05:12] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Wohnzimmer CO Sensor","ieee_address":"0xa4c138e3d813d2bc"},"type":"device_joined"}'
[29.12.2025, 23:05:12] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Wohnzimmer CO Sensor","ieee_address":"0xa4c138e3d813d2bc","status":"started"},"type":"device_interview"}'
[29.12.2025, 23:05:13] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Wohnzimmer CO Sensor","ieee_address":"0xa4c138e3d813d2bc"},"type":"device_announce"}'
[29.12.2025, 23:05:13] z2m: Successfully interviewed 'Wohnzimmer CO Sensor', device has successfully been paired
[29.12.2025, 23:05:13] z2m: Device 'Wohnzimmer CO Sensor' is supported, identified as: Nous Zigbee carbon monoxide (CO) sensor (E12)
[29.12.2025, 23:05:13] z2m: Configuring 'Wohnzimmer CO Sensor'
[29.12.2025, 23:05:13] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Zigbee carbon monoxide (CO) sensor","exposes":[{"access":1,"description":"Indicates if CO (carbon monoxide) is detected","label":"Carbon monoxide","name":"carbon_monoxide","property":"carbon_monoxide","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Current CO concentration","label":"Carbon monoxide value","name":"carbon_monoxide_value","property":"carbon_monoxide_value","type":"numeric","unit":"ppm"},{"access":7,"description":"Triggers self-checking process","label":"Self checking","name":"self_checking","property":"self_checking","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Result of self-checking","label":"Checking result","name":"checking_result","property":"checking_result","type":"enum","values":["ok","error"]},{"access":7,"description":"Sensor preheating status","label":"Preheat","name":"preheat","property":"preheat","type":"binary","value_off":"OFF","value_on":"ON"},{"access":7,"description":"Sensor fault indicator","label":"Fault","name":"fault","property":"fault","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Sensor service life or usage counter","label":"Lifecycle","name":"lifecycle","property":"lifecycle","type":"numeric","unit":"days"},{"access":1,"category":"diagnostic","description":"Battery level in %","label":"Battery","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"category":"diagnostic","description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"E12","options":[],"source":"native","supports_ota":false,"vendor":"Nous"},"friendly_name":"Wohnzimmer CO Sensor","ieee_address":"0xa4c138e3d813d2bc","status":"successful","supported":true},"type":"device_interview"}'
[29.12.2025, 23:05:13] z2m: Successfully configured 'Wohnzimmer CO Sensor'
[29.12.2025, 23:05:19] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Wohnzimmer CO Sensor', payload '{"battery":2,"carbon_monoxide":true,"carbon_monoxide_value":0,"checking_result":null,"device":{"applicationVersion":80,"dateCode":"","friendlyName":"Wohnzimmer CO Sensor","hardwareVersion":1,"ieeeAddr":"0xa4c138e3d813d2bc","manufacturerID":4417,"manufacturerName":"_TZE284_sonkaxrd","model":"E12","networkAddress":8716,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"fault":false,"lifecycle":true,"linkquality":124,"preheat":null,"self_checking":false}'`

`[29.12.2025, 21:21:53] z2m: Publish 'set' 'preheat' to 'Wohnzimmer CO Sensor' failed: 'Error: Value: 'OFF' not found in: [0, 1]'
`

**Comment by Bottesford** [comment]
I'm also getting the exact same problem with these errors:
[10/01/2026, 12:12:27] z2m: Exception while calling fromZigbee converter: Value '0' is not allowed, expected one of ok,error}
[10/01/2026, 12:12:28] z2m: Exception while calling fromZigbee converter: Value 'false' is not allowed, expected one of OFF,ON}
[10/01/2026, 12:12:47] z2m: Exception while calling fromZigbee converter: Value '1' is not allowed, expected one of ok,error}

Battery shows 2% and CO is detected (but battery is full on the device and no CO is detected).

**Comment by Koenkk** [comment]
Fixed!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by focmb** [comment]
I have the same problem with Nous E12 and the dev branch via docker (koenkk/zigbee2mqtt:latest-dev)

{
    "battery": 2,
    "carbon_monoxide": true,
    "carbon_monoxide_value": 0,
    "checking_result": "error",
    "fault": false,
    "last_seen": "2026-01-13T17:49:45.365Z",
    "lifecycle": true,
    "linkquality": 138,
    "self_checking": false
}

Battery is always on 2% and carbon_monoxid is detectd but the sensor itsself shows no CO

`
[2026-01-13 19:12:19] debug:    z2m: Received Zigbee message from '0xa4c138a80e954184', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":10}],"seq":19456}' from endpoint 1 with groupID 0
[2026-01-13 19:12:19] error:    z2m: Exception while calling fromZigbee converter: Value 'false' is not allowed, expected one of 0,1}
[2026-01-13 19:12:19] debug:    z2m: Error: Value 'false' is not allowed, expected one of 0,1
    at Object.from (/app/node_modules/.pnpm/zigbee-herdsman-converters@25.105.0/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:488:27)
    at Object.convert (/app/node_modules/.pnpm/zigbee-herdsman-converters@25.105.0/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:2091:57)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:171:51)
    at processTicksAndRejections (node:internal/process/task_queues:103:5)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:252:17)
[2026-01-13 19:12:19] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0xa4c138a80e954184', payload '{"battery":2,"carbon_monoxide":true,"carbon_monoxide_value":0,"checking_result":"error","fault":false,"last_seen":"2026-01-13T18:12:19.800Z","lifecycle":true,"linkquality":153,"preheat":null,"self_checking":false}'
[2026-01-13 19:12:19] debug:    zh:zstack:unpi:parser: <-- [254,1,100,1,0,100,254,3,68,128,0,1,41,239]
[2026-01-13 19:12:19] debug:    zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100,254,3,68,128,0,1,41,239]
[2026-01-13 19:12:19] debug:    zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
[2026-01-13 19:12:19] debug:    zh:zstack:znp: <-- SRSP: AF - dataRequest - {"status":0}
[2026-01-13 19:12:19] debug:    zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,41,239]
[2026-01-13 19:12:19] debug:    zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,41] - 239
[2026-01-13 19:12:19] debug:    zh:zstack:znp: <-- AREQ: AF - dataConfirm - {"status":0,"endpoint":1,"transid":41}
[2026-01-13 19:12:19] debug:    zh:zstack:unpi:parser: --- parseNext []
`

**Comment by noelarnaud-stack** [comment]
Good evening, 

I installed Zigbee2MQTT Edge, should that work or is that not enough and I missed something? 
That doesn't for me in that way

thanks a lot for all your support

**Comment by Matzebhv** [comment]
2.8.0 does not fix this problem.

<img width="328" height="416" alt="Image" src="https://github.com/user-attachments/assets/30150e00-cb4a-40bb-b449-7a104536aaf5" />

[1.2.2026, 21:07:01] z2m: Publish 'set' 'self_checking' to 'CO-Melder' failed: 'Error: No datapoint defined for 'self_checking''
[1.2.2026, 21:07:01] frontend:api: Sending {"topic":"0xa4c138d888dfa9c0/set","payload":{"self_checking":true}}
[1.2.2026, 21:07:02] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt2/RM_PV_SCHUPPEN', payload '{"alarm":null,"battery":100,"battery_low":false,"enrolled":true,"fault":false,"ias_cie_address":"0x00124b00258ced84","linkquality":45,"max_duration":240,"reliability":"no_fault_detected","restore_reports":true,"smoke":false,"supervision_reports":true,"temperature":-4,"test":false,"update":{"installed_version":-1,"latest_version":-1,"state":null},"voltage":3000,"zone_id":23}'
[1.2.2026, 21:07:02] frontend:api: Sending {"topic":"0xa4c138d888dfa9c0/set","payload":{"self_checking":true}}
[1.2.2026, 21:07:02] z2m: Publish 'set' 'self_checking' to 'CO-Melder' failed: 'Error: No datapoint defined for 'self_checking''

**Comment by tomaszbridge3-dev** [comment]
Same problem here:

{
    "battery": 2,
    "carbon_monoxide": true,
    "carbon_monoxide_value": 0,
    "fault": false,
    "last_seen": "2026-02-11T18:12:51.892Z",
    "lifecycle": true,
    "linkquality": 180,
    "self_checking": false,
    "battery_state": null,
    "checking_result": null,
    "preheat": null
}

**Comment by Elu43** [comment]
You need to delete and add the device again.
