### ISSUE TITLE
Device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7'

### ISSUE THREAD

**Issue by r52alex** [Koenkk/zigbee2mqtt#7405]
Hi,

I have this log in mqtt add-on. Could you support my device? Thank you.

Device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7'

Zigbee2MQTT:warn  2021-05-09 13:39:43: Device '0x847127fffe8d9764' left the network
Zigbee2MQTT:warn  2021-05-09 13:39:48: Device '0x847127fffe8d9764' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Zigbee2MQTT:warn  2021-05-09 13:44:58: Device '0x847127fffe8d9764' left the network
Zigbee2MQTT:warn  2021-05-09 13:44:59: Device '0x847127fffe8d9764' left the network
Zigbee2MQTT:warn  2021-05-09 13:45:36: Device '0x847127fffe8d9764' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Bought this device here
https://aliexpress.ru/item/1005002344798281.html

**Comment by trashographer** [comment]
Same problem, bought 2 items, same link
warning Device '0x847127fffe8d9783' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7' is NOT supported

**Comment by shvirik** [comment]
Dear,

I bought 3, and two works properly and the third one gave me the same error :( Different seller, but the same item (apparently).

Regards,

**Comment by shvirik** [comment]
one additional info. 2/3 devices that work properly are recognized by zigbee2mqtt as TS0121_plug.

**Comment by razmoket89** [comment]
Indeed @shvirik , I bought from the same seller and am having the same problem. The item is recognised as TS011F, but was sold as TS0121 which is working with z2m.

**Comment by shvirik** [comment]
> 
> 
> Indeed @shvirik , I bought from the same seller and am having the same problem. The item is recognised as TS011F, but was sold as TS0121 which is working with z2m.

@razmoket89  do you have an operative TS0121_plug?. Because, I have two working, but they dont  expose the energy sum of consumed energy:

![imagen](https://user-images.githubusercontent.com/74122087/118355687-90311600-b571-11eb-9b2e-78ea25df93d8.png)

Do you have this issue too?

**Comment by r52alex** [comment]
I have one TS0121_plug.it work fine. Exposes  Kwh
![Uploading Screenshot_2021-05-15-13-04-28-562_io.homeassistant.companion.android.jpg…]()

**Comment by razmoket89** [comment]
> > Indeed @shvirik , I bought from the same seller and am having the same problem. The item is recognised as TS011F, but was sold as TS0121 which is working with z2m.
> 
> @razmoket89 do you have an operative TS0121_plug?. Because, I have two working, but they dont expose the energy sum of consumed energy:
> 
> ![imagen](https://user-images.githubusercontent.com/74122087/118355687-90311600-b571-11eb-9b2e-78ea25df93d8.png)
> 
> Do you have this issue too?

I dont own any TS0121_plug, sorry.

**Comment by shvirik** [comment]
> I have one TS0121_plug.it work fine. Exposes Kwh
> Uploading Screenshot_2021-05-15-13-04-28-562_io.homeassistant.companion.android.jpg…

Thanks. I don't know why mine ones dont give me the sum values.

**Comment by shvirik** [comment]
> 
> 
> > > Indeed @shvirik , I bought from the same seller and am having the same problem. The item is recognised as TS011F, but was sold as TS0121 which is working with z2m.
> > 
> > 
> > @razmoket89 do you have an operative TS0121_plug?. Because, I have two working, but they dont expose the energy sum of consumed energy:
> > ![imagen](https://user-images.githubusercontent.com/74122087/118355687-90311600-b571-11eb-9b2e-78ea25df93d8.png)
> > Do you have this issue too?
> 
> I dont own any TS0121_plug, sorry.

Thanks

**Comment by Koenkk** [comment]
Added now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by r52alex** [comment]
Thank you very much!

**Comment by Koenkk** [comment]
Does somebody have the TuYa gateway? If yes please help with this issue: https://github.com/Koenkk/zigbee-herdsman-converters/pull/2587#issuecomment-842416346

**Comment by manJerky** [comment]
Just tried and got unsupported message on dev branch (1.18.3-dev):

`Device '0x847127fffe8d9689' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
`

Shouldn't there be no issue when the model and manufacturer name are the same or am I misunderstanding?

**Comment by pszafer** [comment]
hi, I got new plugs and unsupported as well:
```
2021-05-26 13:15:05: Device '0x847127fffe8d8686' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_ew3ldmgx' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

should I create PR against - https://github.com/Koenkk/zigbee-herdsman-converters/blob/ba9e37c01e493df1d51e960df7aa26b39faa316e/devices/tuya.js#L649-L670 or just wait?

**Comment by Koenkk** [comment]
@pszafer is it this plug https://zigbee.blakadder.com/Tuya_TS011F.html ?

**Comment by pszafer** [comment]
manufacter name is different but looks very similar. https://a.aliexpress.com/_uzbEDB

**Comment by Koenkk** [comment]
@pszafer added, 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by pszafer** [comment]
Thanks!

**Comment by kotyla** [comment]
Hello,

I've got another TS011F plug not supported. I've tried to use instruction how to support new devices but I failed (seems too complicated for me). I've also tried dev branch.

Is it possible to add it ?
Thank you.

`Device '0x60a423fffeff96db' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_jvzvulen' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
`
![ts011f-2](https://user-images.githubusercontent.com/8727347/124599598-209b2100-de66-11eb-8405-72ecdf156108.JPG)
![ts011f-1](https://user-images.githubusercontent.com/8727347/124599599-21cc4e00-de66-11eb-93f7-293108052d48.JPG)

**Comment by david08154711** [comment]
I have a problem too
Warning device '0x84fd27fffece9981' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_mraovvmm' is NOT supported

I've already switched to dev branch.

(description: 'Smart plug (with power monitoring)')

the manufacturerName '_TZ3000_mraovvmm' is not contained in the tuya.js

**Comment by Koenkk** [comment]
@david08154711 added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by miit86** [comment]
David,

Did you manage to get your "After Power Outage" option set-up?

**Comment by KMDobrev** [comment]
> Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name **'_TZ3000_w0qqde0g**

I also have one of these devices and Energy measurements are not displayed.

**Comment by dominikkarall** [comment]
I also got an unsupported device
TS0011F
_TZ3000_nfnmi125

Can you please add this one? Thx!

**Comment by KMDobrev** [comment]
Hallo,

_TZ3000_mraovvmm

This doesn't work either.

![Screenshot_20211116-201522](https://user-images.githubusercontent.com/77675496/142050741-766d56a1-8052-4851-af8d-437be614ff30.jpg)
![Screenshot_20211116-201623](https://user-images.githubusercontent.com/77675496/142050781-15f85e51-7691-4f33-b4f4-47fe88fef1b3.jpg)

**Comment by wkryzel** [comment]
Hallo,

_TZ3000_x2ddiwsv

This doesn't work either.

**Comment by n8schicht17** [comment]
Hi,
could you please also support this one?

Model: TS011F
Manufacturer: _TZ3000_cphmq0q7

It's not reporting power, current, voltage, energy

Thanks a lot!

**Comment by Koenkk** [comment]
@n8schicht17 that issue has just been fixed in the dev branch.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by KMDobrev** [comment]
> @n8schicht17 that issue has just been fixed in the dev branch.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Thank you🙏

**Comment by yukeiw** [comment]
Hi there,

Do you think you could add the one below as well?

Model: TS011F
Manufacturer:_TZ3000_cymsnfvf

power, current, voltage, energy are missing.

Much appreciated!

**Comment by simie7** [comment]
> I also got an unsupported device TS0011F _TZ3000_nfnmi125
> 
> Can you please add this one? Thx!

@dominikkarall you can get it working reading [this](https://github.com/Koenkk/zigbee2mqtt/issues/9493#issuecomment-981153732) issue.

The problem left is energy monitoring, it's not yet supported, as uses new undeclared cluster for this.

**Comment by KMDobrev** [comment]
In my case, these two models still do not show energy measurement in the Edge version.

_TZ3000_ew3ldmgx

_TZ3000_mraovvmm

**Comment by Koenkk** [comment]
@KMDobrev can you post the data/database.db entry of your devices?

**Comment by KMDobrev** [comment]
{"id":26,"type":"Router","ieeeAddr":"0x540f57fffeddebbc","nwkAddr":5067,"manufId":4098,"manufName":"_TZ3000_ew3ldmgx","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_ew3ldmgx","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db4ae","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db4ae","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db4ae","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":680236614},"lastSeen":1639678653689,"useImplicitCheckin":true}

**Comment by Koenkk** [comment]
@KMDobrev what model is displayed in the z2m frontend, `TS011F_plug_3` or `TS011F_plug_1`?

**Comment by KMDobrev** [comment]
> @KMDobrev what model is displayed in the z2m frontend, `TS011F_plug_3` or `TS011F_plug_1`?

This is the other



{"id":40,"type":"Router","ieeeAddr":"0x84fd27fffece7f84","nwkAddr":15042,"manufId":4098,"manufName":"_TZ3000_mraovvmm","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_mraovvmm","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db4ae","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db4ae","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db4ae","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":680236614},"lastSeen":1639679399977,"useImplicitCheckin":true}

**Comment by KMDobrev** [comment]
> `TS011F_plug_1`?

Both the same

TS011F_plug_1

**Comment by Koenkk** [comment]
@KMDobrev then you are not on the latest edge, uninstall and reinstall to upgrade.

**Comment by KMDobrev** [comment]
> @KMDobrev then you are not on the latest edge, uninstall and reinstall to upgrade.

Sorry

TS011F_plug_3

**Comment by ferropolis** [comment]
> @KMDobrev then you are not on the latest edge, uninstall and reinstall to upgrade.

Hey @Koenkk any information or timetable when will it be available in vanilla mode (normal Zigbee2MQTT without Edge)?
Thanks

**Comment by Koenkk** [comment]
@ferropolis release is on every 1st of the month (so 1 January next release)

**Comment by KMDobrev** [comment]
> @ferropolis release is on every 1st of the month (so 1 January next release)

I uninstalled and reinstalled Edge but the problem persists.

In the Edge it say TS011F_plug_3
In the Normal stable version it say TS011F_plug_1

**Comment by frederikbove** [comment]
I'm trying to add the same device: 
Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_v1pdxuqq'

**Comment by mkotek** [comment]
In my case, just got 4 of SHP15 marked as _TZ3000_u5u4cakc

**Comment by Koenkk** [comment]
@frederikbove added `https://github.com/Koenkk/zigbee2mqtt/issues/7405` (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

@mkotek will work in stable with the next release (1 January)

**Comment by mortelil** [comment]
Hello!
I have a XH-002P plug, identified as TS011F_plug_1 - _TZ3000_v1pdxuqq in the latest edge version. Power, voltage, current and energy is marked as 'Null' in the z2m interface, power switch works. Hope for support for this. This is the info from database.db:

{"id":38,"type":"Router","ieeeAddr":"0xa4c138aeff547348","nwkAddr":7829,"manufId":4417,"manufName":"_TZ3000_v1pdxuqq","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_v1pdxuqq","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"20480":1,"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2}},"manuSpecificTuya_3":{"attributes":{"53264":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff079473","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1640547141776,"useImplicitCheckin":true}

**Comment by tansuka** [comment]
Any luck for same device but with the manufacturer _TZ3000_typdpbpg 
Thank you very much

**Comment by mortelil** [comment]
I updated my Zigbee2MQTT edge today, and the _TZ3000_v1pdxuqq still wont work. Is this supposed to be available in the next stable release? 
I get the following errors in my log when I plug it in:

Failed to configure '0xa4c138aeff547348', attempt 2 (Error: Bind 0xa4c138aeff547348/1 haElectricalMeasurement from '0x00212effff079473/1' failed (Error: status: 130) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/tuya.js:1084:13) at Configure.configure (/app/lib/extension/configure.ts:115:13))

Failed to ping '0xa4c138aeff547348' (attempt 1/1, Read 0xa4c138aeff547348/1 genBasic(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received))

**Comment by WouterJN** [comment]
After the latest update my plug (_TZ3000_u5u4cakc) works fine, thnx!

**Comment by KochergaAlex** [comment]
Hi,
I have this log in mqtt add-on. Could you support my device? 
Thank you.

Zigbee model 'TS011F' and manufacturer name '_TZ3000_cfnprab5' is NOT supported

**Comment by KochergaAlex** [comment]
Zigbee model 'TS011F' and manufacturer name '_TZ3000_cfnprab5' is NOT supported

Smart Power Strip  -  Model: SM-SO306E-1Z

**Comment by kkossev** [comment]
@frederikbove is your **_TZ3000_v1pdxuqq** model reporting any power or energy readings?

> inClusterList":[3,4,5,6,57344,57345,0]
There are no power or energy clusters there, nor the usual Tuya EF00 cluster ..

**Comment by Koenkk** [comment]
@kkossev based on the cluster list, it doesn't support this indeed. Moved it to TS011F_plug_2 (Smart plug (without power monitoring))

**Comment by JJussi** [comment]
I just received multiple TS011F, but with different  manufacturer name '_TZ3000_typdpbpg'. These are with power monitoring.  Could this be added to the supported models and deployed to HA side?

**Comment by Koenkk** [comment]
@JJussi `_TZ3000_typdpbpg` is already supported in z2m 1.23.0

**Comment by JJussi** [comment]
OK. 
My HA z2m add-on is 1.20.0-1, so... I need to wait that a newer version is published.  Or is there an easy way to install a newer version to my system?

**Comment by Koenkk** [comment]
@JJussi HA should already show an update, not sure how to force it but uninstall -> install again may fix it.

**Comment by SAMUD** [comment]
I also just received an TS011F, this time with model ID TZ3000_gjnozsaz.

`Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_gjnozsaz'`

It is[ this one](https://www.ebay.de/itm/334215428684), so it should also support power metering.

Would be cool If you could add it. Thanks :)

**Comment by sermayoral** [comment]
Hi! I need an smart plug and i have seen this interesting model. I have read in https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html a broken reporting functionality. Is it compatible right now or i should buy the shp13 old model?

Thanks!!

**Comment by JJussi** [comment]
I have those power plugs and they work fine...
{
    "current": 0.05,
    "energy": 0.27,
    "linkquality": 0,
    "power": 10,
    "power_outage_memory": "restore",
    "state": "ON",
    "voltage": 232
}

**Comment by SAMUD** [comment]
> I also just received an TS011F, this time with model ID TZ3000_gjnozsaz.
> 
> `Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_gjnozsaz'`
> 
> It is[ this one](https://www.ebay.de/itm/334215428684), so it should also support power metering.
> 
> Would be cool If you could add it. Thanks :)

I made a pull request and found out that this device was already added. It was just my Docker container which was a "little bit" outdatted :D

**Comment by SAMUD** [comment]
> Hi! I need an smart plug and i have seen this interesting model. I have read in https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html a broken reporting functionality. Is it compatible right now or i should buy the shp13 old model?
> 
> Thanks!!

You can set a polling intervall in which the data is read from the plug. In my case - where I only need the cunsumption - , it works without any problems since thre days now.

**Comment by foreignerrad** [comment]
Hi,
I have this log in mqtt add-on. Could you support my device?
Thank you.

Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5' is NOT supported

**Comment by muesli** [comment]
Similar here:

```
{"level":"warning","message":"Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_ksw8qtmt'"}
```

**Comment by Koenkk** [comment]
@muesli `_TZ3000_ksw8qtmt` is supported in the latest dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by treynaer** [comment]
Hi,
Model TS011F of Manufacturer _TZ3000_ky0fq4ho also shows up as not supported.
https://www.aliexpress.com/item/1005003473545843.html

**Comment by Koenkk** [comment]
@treynaer added

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by janpieper** [comment]
I have some `_TZ3000_ksw8qtmt` devices. After switching to the dev branch about a week ago, they work without any problems :partying_face:

Thanks everyone :heart:

**Comment by tipunov-ao** [comment]
Dear Koenkk, add please "_TZ3000_cjrngdr3" device.

**Comment by osmutalip** [comment]
Dear Koenkk, similar issue. Can you help add in "_TZ3000_v4mevirn" as well? Thank you.

**Comment by Koenkk** [comment]
@osmutalip added.

**Comment by Koenkk** [comment]
@klikodes `_TZ3000_zloso4jk` has already been added (currently in the dev branch only but will be in the next release on 1 June)

**Comment by osmutalip** [comment]
@Koenkk Sincere apologies, the device was wrongly identifying as TS011F earlier. Now that it can pair, it turns out to be the wrong device. Based on the website, the correct device should be "[Zemismart ZIGBEE-B09-UK](https://www.zigbee2mqtt.io/devices/ZIGBEE-B09-UK.html#zemismart-zigbee-b09-uk)"  for manufacturer name "_TZ3000_v4mevirn"

I should have validated the zigbee model properly before the request. Sorry!

**Comment by Koenkk** [comment]
@osmutalip moved it to ZIGBEE-B09-UK

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Koenkk** [comment]
@looknw added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by lst3245** [comment]
I got a _TZ3000_r6buo8ba, could you please add it? Thank you.

**Comment by lst3245** [comment]
> @lst3245 `_TZ3000_r6buo8ba` is already supported in the latest dev (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Ops, sorry for bothering you. I must have looked into the wrong commit of the tuya.js as I can clearly see it's already in the latest commit. Thanks anyway!

**Comment by shuxing** [comment]
Hi, @Koenkk, could you please support for _TZ3000_okaz9tjs?

> 'TS011F' and manufacturer name _TZ3000_okaz9tjs

**Comment by shuxing** [comment]
> Hi, @Koenkk, could you please support for _TZ3000_okaz9tjs?
> 
> > 'TS011F' and manufacturer name _TZ3000_okaz9tjs

never mind, found it's added couple of days ago, updating docker and Voilà, it's working like a charm, zigbee2mqtt is simply awesome!!!

**Comment by WildeRNS** [comment]
Please add new manufacturer -TZ3000_ss98ec5d, this is moes socket: https://a.aliexpress.com/_vcuRUn

**Comment by Koenkk** [comment]
@WildeRNS added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by csirek** [comment]
Here is my unsupported device, this is a Blitzwolf BW-SHP15: '_TZ3000_u5u4cakc'. Thank You!

**Comment by tomekso** [comment]
Hello @Koenkk,
Could you add the following socket?
Zigbee Model    TS011F
Zigbee Manufacturer    _TZ3000_r6buo8ba
Support status    Not supported
IEEE Address    0x70b3d52b6000941f
Network address    0xB1A9
Firmware build date    20210720
Firmware version    20B-TZSKT11BS3.4

**Comment by Koenkk** [comment]
`_TZ3000_u5u4cakc` and `_TZ3000_r6buo8ba` are already supported in z2m 1.27.0

**Comment by tomekso** [comment]
_TZ3000_r6buo8ba also  :) thx!

**Comment by hossamnagy** [comment]
Hi @Koenkk , I'm having the same error
Can you please add support for below device

Zigbee Model
TS011F
Zigbee Manufacturer
_TZ3000_cfnprab5

Many thanks

**Comment by Koenkk** [comment]
@hossamnagy `_TZ3000_cfnprab5` is already supported in z2m 1.27.0

**Comment by Malaysk** [comment]
Hi @Koenkk , I'm having the same error
Can you please add support for below device
Zigbee model  
TS011F
Producer Zigbee   
_TZ3000_b28wrpvx
Support status
Not supported

**Comment by Koenkk** [comment]
@Malaysk added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by MvdB1982** [comment]
> @MvdB1982 I have the exact same model/firmware, and the exact same issues.
> 
> Maybe we should open a separate issue?

Sure!

**Comment by hiddevanbrussel** [comment]
Issue with power measuring Power KwH

![image](https://user-images.githubusercontent.com/54264973/194559191-25faf862-505c-4571-9243-184c4a0bd11b.png)

Eenvoudige naam
Wasmachine
Omschrijving
Laatst gezien
N/A
Beschikbaar
Online
Apparaat type
Router
Zigbee model
TS011F
Zigbee Fabrikant
_TZ3000_r6buo8ba
Omschrijving
Smart plug (with power monitoring by polling)
Ondersteuningsstatus
Ondersteund

IEEE adres
0x70b3d52b600142d1
Netwerkadres
0xC992
Firmware build date
20210625
Firmwareversie
20B+TZSKT41BS101
Fabrikant
[TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model
[TS011F_plug_3](https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3)
Batterijniveau
Interview voltooid
Waar

![image](https://user-images.githubusercontent.com/54264973/194559323-374d9b38-8f7b-475b-94f5-ec42e15a8a2d.png)

**Comment by elcool0r** [comment]
Hello there!
I've got the same problem with this plug:
```
Friendly name
0xa4c138f1450185e5
Description
Last seen
N/A
Availability
[Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type
Router
Zigbee Model
TS011F
Zigbee Manufacturer
_TZ3000_rdfh8cfs
Support status
Not supported

IEEE Address
0xa4c138f1450185e5
Network address
0xDE45

```

`Warning 2022-10-11 14:55:23Device '0xa4c138f1450185e5' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_rdfh8cfs' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html`

is it possible to add this too?

**Comment by NickBarkerTV** [comment]
Hi folks. I also have a TS011F_plug_3 that correctly exposes everything except energy and can't be updated OTA. The manufacturer is _TZ3000_okaz9tjs. @Koenkk, surely it can't be scalable for you to put a pull request in for every new device? That must be a full time job! (And, from what I have read, you seem to be awesome at it).
![Image 1](https://user-images.githubusercontent.com/115584751/195176582-f52aedb5-6ad5-42bc-8973-5c7b978aeea6.png)
![Image 2](https://user-images.githubusercontent.com/115584751/195176781-1d8c8c93-da1a-4f36-bb7a-2cb9a6d94942.png)

**Comment by thve25** [comment]
I've a "_TZ3000_r6buo8ba" since several days that does not report energy use.

{
    "child_lock": "LOCK",
    "current": 0.98,
    "indicator_mode": "on",
    "linkquality": 189,
    "power": 200,
    "power_outage_memory": "restore",
    "state": "ON",
    "voltage": 217,
    "device": {
        "applicationVersion": 160,
        "dateCode": "20210625",
        "friendlyName": "smartplug-PC",
        "hardwareVersion": 3,
        "ieeeAddr": "0x70b3d52b6001415a",
        "manufacturerID": 4660,
        "manufacturerName": "_TZ3000_r6buo8ba",
        "model": "TS011F_plug_3",
        "networkAddress": 14959,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "20B+TZSKT41BS101",
        "stackVersion": 1,
        "type": "Router",
        "zclVersion": 2
    },
    "energy": null,
    "update": {
        "state": null
    },
    "update_available": null
}


Strange thing is that I have the same plug (_TZ3000_r6buo8ba), but one that I ordered a few weeks earlier, that does report energy use:


{
    "child_lock": "LOCK",
    "current": 0.54,
    "energy": 27.66,
    "linkquality": 87,
    "power": 87,
    "power_outage_memory": "on",
    "state": "ON",
    "voltage": 231,
    "device": {
        "applicationVersion": 160,
        "dateCode": "20210720",
        "friendlyName": "smartplug-extra",
        "hardwareVersion": 2,
        "ieeeAddr": "0x70b3d52b6000953e",
        "manufacturerID": 0,
        "manufacturerName": "_TZ3000_r6buo8ba",
        "model": "TS011F_plug_3",
        "networkAddress": 53012,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "20B-TZSKT11BS3.4",
        "stackVersion": 1,
        "type": "Router",
        "zclVersion": 2
    },
    "indicator_mode": null,
    "update": {
        "state": null
    },
    "update_available": null
}

**Comment by tOOmki** [comment]
Different FW:
"dateCode": "20210625",
"softwareBuildID": "20B+TZSKT41BS101", - these don't work
vs
"dateCode": "20210720",
"softwareBuildID": "20B-TZSKT11BS3.4", - these works

**Comment by thve25** [comment]
> Different FW: "dateCode": "20210625", "softwareBuildID": "20B+TZSKT41BS101", - these don't work - I have 3 of them and I am also missing energy counting vs "dateCode": "20210720", "softwareBuildID": "20B-TZSKT11BS3.4", - these works

Updating the firmware is not possible:

`Info 2022-10-12 11:16:11Checking if update available for 'smartplug-PC'
Debug 2022-10-12 11:16:11Check if update available for '0x70b3d52b6001415a' (TS011F)
Info 2022-10-12 11:16:11MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"smartplug-PC"},"error":"Failed to check if update available for 'smartplug-PC' (Failed to find endpoint which support OTA cluster)","status":"error","transaction":"wd7m3-2"}'
Error 2022-10-12 11:16:11Failed to check if update available for 'smartplug-PC' (Failed to find endpoint which support OTA cluster)
Debug 2022-10-12 11:16:11AssertionError [ERR_ASSERTION]: Failed to find endpoint which support OTA cluster at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:248:9) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:130:19) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:194:67) at EventEmitter.emit (node:events:525:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:140:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:94:27) at WebSocket.emit (node:events:513:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20) at Receiver.emit (node:events:513:28)`

I hope this problem can be solved in zigbee2mqtt because I bought them especially for energy monitoring.

**Comment by maciejs804** [comment]
Hi,
I have new device TS011F which isn't supported by [Zigbee2MQTT]
Model Zigbee TS011F
zigbee_manufacturer _TZ3000_u5u4cakc
Support status not_supported

**Comment by Koenkk** [comment]
@maciejs804 `_TZ3000_u5u4cakc` is already supported in the latest dev  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by peversnl** [comment]
Hi @Koenkk, I bought 3 smartplug from Lidl hoping for a smooth integration including power/energy measurements in HA, however this version seems not to be supported, can you help?

Zigbee model
TS011F
Zigbee Fabrikant
_TZ3000_j1v25l17
Ondersteuningsstatus
Niet ondersteund

**Comment by daangel27** [comment]
Hi @Koenkk , 
Can you please add support for below device.
Zigbee model:  **TS011F**
manufacturer name:  **_TZ3000_rdfh8cfs**
Support status: Not supported

Device description :
Brand name: **FDTEK**
Model: **NAS-WR01B**
[https://www.amazon.fr/gp/product/B0B469461P/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1](url)

Many thanks for your support.
Regards

**Comment by Koenkk** [comment]
@peversnl is this a `HG08673`?

@daangel27 `_TZ3000_rdfh8cfs` will be supported in the next z2m release on 1 November.

**Comment by peversnl** [comment]
> @peversnl is this a `HG08673`?
> 
> @daangel27 `_TZ3000_rdfh8cfs` will be supported in the next z2m release on 1 November.

Correct!
![16668041042895689012169942652406](https://user-images.githubusercontent.com/92923248/198091484-f019cd85-e67b-4704-8659-36ac045e5632.jpg)

**Comment by ritonbe** [comment]
> Hi @Koenkk , Can you please add support for below device. Zigbee model: **TS011F** manufacturer name: **_TZ3000_rdfh8cfs** Support status: Not supported
> 
> Device description : Brand name: **FDTEK** Model: **NAS-WR01B** [https://www.amazon.fr/gp/product/B0B469461P/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1](url)
> 
> Many thanks for your support. Regards

Just get 8 of them from Amazon.fr ... I'm happy to read that support will be available into the next release.

Regards

**Comment by dE1l** [comment]
@Koenkk please, add this https://aliexpress.ru/item/1005003698857421.html
Router
TS011F
_TZ3000_hdopuwv6
![IMG_0564 — малый размер](https://user-images.githubusercontent.com/8767620/201999848-1d88bb0e-23b2-4c19-ac93-9129ac482ef9.jpeg)

vendor AUBESS
with power monitor

**Comment by Koenkk** [comment]
@daangel27  already supported in z2m 1.28.2

**Comment by romarcis** [comment]
Hi @Koenkk, can you please add support for below device?
I have two smart plug "unsupported".

Zigbee Model
TS011F
Zigbee Manufacturer
_TZ3000_cehuw1lw

Thanks

**Comment by Koenkk** [comment]
@romarcis `_TZ3000_cehuw1lw` is already supported in the dev branch and in the next release on 1 December.

**Comment by peversnl** [comment]
@Koenkk, were you able to have a look at this one?
HG08673

**Comment by Koenkk** [comment]
@peversnl `_TZ3000_j1v25l17` will be supported in the next release on 1 December.

**Comment by peversnl** [comment]
@Koenkk, thanks you!

**Comment by lennelei** [comment]
Hi,
I probably have the same issue, I just bought a bunch of Nous A1Z plugs and they are "unsupported".
Manufacturer is `_TZ3000_2putqrmw`
`Device '0xa4c13807df931523' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_2putqrmw' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html`
Thank you in advance.

**Comment by Koenkk** [comment]
@lennelei will be supported in tomorrow's new release.

**Comment by Koenkk** [comment]
@simguth it is supported in z2m 1.28.3

**Comment by simguth** [comment]
@Koenkk 

Oups, my bad sorry ! I just updated, it works very fine.

I take this opportunity to sincerely thank you for the quality of this Z2M service and your very fast and always precise support, very good job

Ludovic

**Comment by mythingx** [comment]
@Koenkk I bought one Aubess that looks like the one posted by peversnl. 

But the device i bought have a different Manufacturer ID. Please add this device . Your supoprt is higly appreciated!

 ---> Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_gvn91tmx'

If you need more info,let me know.
Thank you.

**Comment by Koenkk** [comment]
@mythingx should work out-of-the-box in z2m 1.28.4

**Comment by BnmaDavid** [comment]
Dear team - new another combination manufacturer / model... for same item...
warn 2022-12-29 17:07:31: Device '0xa4c138a05595d64b' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_gvn91tmx' is NOT supported - thx for adding

**Comment by Koenkk** [comment]
@BnmaDavid should work in 1.28.4

**Comment by BnmaDavid** [comment]
Yes, sorry, it works well, i had still old version. Now this version 1.7.0 (1.28.4) is OK

**Comment by Shadow505** [comment]
Hi  @Koenkk, I have the same issue but again, with a different manufacture id:

Device '0xa4c13851ce4c7477' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cjrngdr3' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

Would appreciate a fix. Thanks in advance

**Comment by fl1p1** [comment]
It seems this one isn't supported: https://nl.aliexpress.com/item/1005004910203202.html?spm=a2g0o.order_list.order_list_main.11.f02279d2cJGJlf&gatewayAdapt=glo2nld
Model: TS011F
Manufacturer: _TZ3000_gvn91tmx

**Comment by darkiller22003** [comment]
Hi @Koenkk , Can you please add support for the below device? 
Zigbee model: TS011F 
Manufacturer Name: _TZ3000_okaz9tjs 
Support status: Not supported

**Comment by darkiller22003** [comment]
Hi @Koenkk ,
Can you please add support for the below device?
Zigbee model: TS011F
Manufacturer Name: _TZ3000_okaz9tjs
Support status: Not supported

**Comment by Koenkk** [comment]
@darkiller22003 is supported in z2m 1.29.2

**Comment by MirFei** [comment]
Hi @Koenkk , Can you please add support for the below device?
Zigbee model: TS011F
Manufacturer Name:_TZ3000_0zfrhq4i
Support status: Not supported

**Comment by Koenkk** [comment]
@MirFei update to z2m 1.30.0

**Comment by michl1003** [comment]
> @lennelei will be supported in tomorrow's new release.

sorry for the stupid question but how do i get the new release for Zigbee2MQTT on a loxberry? my version on loxberry is v1.6.0. can anyone help me please because i do have the same problem with TZ3000_2putqrmw...

**Comment by shvirik** [comment]
Hi @Koenkk , Can you please add support for the below device?
Zigbee model: TS011F
Manufacturer Name:_TZ3000_rdfh8cfs
Support status: Not supported

I've checked the post and appear as supported, isn,t it? (Dec 13, 2022)

**Comment by marceldejongnl** [comment]
@Koenkk 

Zigbee model 'TS011F' and manufacturer name '_TZ3000_hdopuwv6' is NOT supported

Could you add it please?
