### ISSUE TITLE
CC2531 Touchlink Commands with IKEA TRADFRI don't work (works with other bulb tested), weird behaviour

### ISSUE THREAD

**Issue by clemwo** [Koenkk/zigbee2mqtt#8535]
## What happened
I sent a scan MQTT message to zigbee2mqtt/bridge/request/touchlink/scan with empty payload. Ikea Tradfri bulb is in vicinity and turned on. It returns 

```
    "data": {
        "found": []
    },
    "status": "ok"
```
If I try to factory reset I get the error: 
```
"error": "Failed to factory reset device through Touchlink",
    "status": "error"
```

What's interesting is that scan, identify and factory reset work fine with the Müller-Licht bulb I have. 
The weird part is that when Im sniffing the traffic in the channel the Bulb is on (25) I can always see the scan request sent out from Z2M and only see a scan response if I turn off the power from the IKEA bulb, then turn it back on and then send the scan request. But even when I see a scan response, Z2M doesnt show anything in the results. If I then try to send another scan request, the IKEA bulb apparently decides not to answer another time... why?

My assumption is that *maybe* this is some sort of security feature of IKEA that the bulbs dont reply to every random touchlink command. Maybe they also check the MAC-Adress to see if the device the touchlink command is sent from, is from IKEA themselves? What supports my theory is the fact that if I use the TRADFRI remote control, I can easily provoke the bulb to send out multiple scan responses within a shorter amount of time.

I'm now just really intrigued why this happens. Here is a pastebin with the sniffed packages:
https://pastebin.com/AHBnp2JG

The first two packet is the scan request and the scan response. The third packet is just a scan request that gets no response. I dont know if this helps at all.
It would be really interesting if someone else could try out the Touchlink commands with Ikea products.

## What did you expect to happen
I expected to see the Ikea Tradfri bulb in the scan request and I also expected to be able to factory reset it via Touchlink.

## Debug info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: CC2531
Adapter firmware version: CC2531_DEFAULT_20201127 ZStack 1.2

**Comment by Koenkk** [comment]
Found & fixed the issue, can you confirm?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by clemwo** [comment]
> Found & fixed the issue, can you confirm?
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Thank you so much, this really makes my day. I'm on the road currently and will try it out on monday.  
Your work is really appreciated, Z2M is great

**Comment by clemwo** [comment]
> Found & fixed the issue, can you confirm?
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Unfortunately it still doesn't work for me. Im on Home Assistant OS Supervised, deinstalled Z2M and installed the Z2M Edge Addon. 
My IKEA bulb resides on channel 25 here is the log output (with actived Zigbee Herdsman debugging):

https://pastebin.com/LsR1ek8z

One thing that the dev branch already fixed for me is the fact that the device responds to multiple scan requests (I can see when sniffing, not as output on MQTT though). Before that the bulb only replied to the first scan request and then didnt only when I cut off the bulb from power. That was probably the issue with the transaction ID being 0 but now that it is random every scan request, this works fine.

**Comment by Koenkk** [comment]
> One thing that the dev branch already fixed for me is the fact that the device responds to multiple scan requests (I can see when sniffing, not as output on MQTT though).

This is the only thing I fixed, what is the problem now?

**Comment by clemwo** [comment]
> > One thing that the dev branch already fixed for me is the fact that the device responds to multiple scan requests (I can see when sniffing, not as output on MQTT though).
> 
> This is the only thing I fixed, what is the problem now?

Excuse me, I think my original post wasn't clear enough (it was late at night). There were actually two issues. The first one was the transaction ID which is now fixed. 
Unfortunately the IKEA bulbs still can't be found. If I publish an MQTT packet with a Touchlink scan request the IKEA bulb simply doesn't show up although the IKEA bulb responds in time with a scan response: 
```
{
    "data": {
        "found": []
    },
    "status": "ok"
}
```
Identify and Reset to Factory also don't work, Im assuming this also has to do with the fact that the scan response doesn't get recognized.

**Comment by clemwo** [comment]
> I couldn't reproduce the issue were the bulb sends a scan response but it does not show up in z2m, could you provide the herdsman debug logging of this? (please keep log as short as possible)
> 
> See https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

Hey, I have already provided the logs in the previous reply:

> Unfortunately it still doesn't work for me. Im on Home Assistant OS Supervised, deinstalled Z2M and installed the Z2M Edge Addon.
My IKEA bulb resides on channel 25 here is the log output (with actived Zigbee Herdsman debugging):
> https://pastebin.com/LsR1ek8z

Is this the log you are looking for? In the link you supplied it says that the Zigbee Herdsman debugging shows up in logs on Home Assistant OS Supervised

**Comment by Koenkk** [comment]
Missed that sorry, found & fixed the issue.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by clemwo** [comment]
> Missed that sorry, found & fixed the issue.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

It works, thank you so much for your work, I can't thank you enough. A virtual coffee is being sent your way!
